// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.Coaching.Data;

#nullable disable

namespace Spectrometre.Modules.Coaching.Data.Migrations
{
    [DbContext(typeof(CoachingDbContext))]
    partial class CoachingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("coaching")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.Coaching.Entities.AnamneseCoaching", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GenereeParIa")
                        .HasColumnType("boolean");

                    b.Property<int>("LienCoachingId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LienCoachingId")
                        .IsUnique();

                    b.ToTable("AnamnesesCoaching", "coaching");
                });

            modelBuilder.Entity("Spectrometre.Modules.Coaching.Entities.LienCoaching", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AccepteLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClotureLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CoachUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InvitationId")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("SuiviUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachUserId");

                    b.HasIndex("SuiviUserId");

                    b.ToTable("LiensCoaching", "coaching");
                });

            modelBuilder.Entity("Spectrometre.Modules.Coaching.Entities.ObjectifCoaching", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Atteinte")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Moyens")
                        .HasColumnType("text");

                    b.Property<int?>("Note")
                        .HasColumnType("integer");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<int>("PeriodeObjectifsCoachingId")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodeObjectifsCoachingId");

                    b.ToTable("ObjectifsCoaching", "coaching");
                });

            modelBuilder.Entity("Spectrometre.Modules.Coaching.Entities.PeriodeObjectifsCoaching", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archivee")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<int>("LienCoachingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LienCoachingId", "Archivee");

                    b.ToTable("PeriodesObjectifsCoaching", "coaching");
                });

            modelBuilder.Entity("Spectrometre.Modules.Coaching.Entities.ObjectifCoaching", b =>
                {
                    b.HasOne("Spectrometre.Modules.Coaching.Entities.PeriodeObjectifsCoaching", "Periode")
                        .WithMany("Objectifs")
                        .HasForeignKey("PeriodeObjectifsCoachingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("Spectrometre.Modules.Coaching.Entities.PeriodeObjectifsCoaching", b =>
                {
                    b.Navigation("Objectifs");
                });
#pragma warning restore 612, 618
        }
    }
}
