// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.Missions.Data;

#nullable disable

namespace Spectrometre.Modules.Missions.Migrations
{
    [DbContext(typeof(MissionsDbContext))]
    [Migration("20260821160000_AddMissionMotifAnnulation")]
    partial class AddMissionMotifAnnulation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("missions")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccesDifficile")
                        .HasColumnType("boolean");

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<string>("CompetencesTravaillees")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulte")
                        .HasColumnType("integer");

                    b.Property<string>("DureeEstimee")
                        .HasColumnType("text");

                    b.Property<string>("Lieu")
                        .HasColumnType("text");

                    b.Property<string>("MotifAnnulation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("NiveauEncadrement")
                        .HasColumnType("integer");

                    b.Property<int>("ParticulierProfileId")
                        .HasColumnType("integer");

                    b.Property<bool>("PortDeCharge")
                        .HasColumnType("boolean");

                    b.Property<bool>("PresenceAnimaux")
                        .HasColumnType("boolean");

                    b.Property<bool>("PresenceEscaliers")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("RemunerationMontant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RisqueParticulier")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParticulierProfileId");

                    b.HasIndex("Statut");

                    b.ToTable("Missions", "missions");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.MissionAcceptation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AccepteeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CoachUserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DecideeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JeuneProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JeuneProfileId");

                    b.HasIndex("MissionId");

                    b.ToTable("MissionAcceptations", "missions");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.MissionEvaluationParticulier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AccepteraitNouvelleMission")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AttitudeRespectueuse")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ConsignesComprises")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MissionAcceptationId")
                        .HasColumnType("integer");

                    b.Property<string>("PointsAAmeliorer")
                        .HasColumnType("text");

                    b.Property<string>("PointsPositifs")
                        .HasColumnType("text");

                    b.Property<bool?>("Ponctualite")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TacheRealiseeCorrectement")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MissionAcceptationId")
                        .IsUnique();

                    b.ToTable("MissionEvaluationsParticulier", "missions");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.MissionPreparationCoche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Coche")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MissionAcceptationId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MissionAcceptationId", "ItemKey")
                        .IsUnique();

                    b.ToTable("MissionPreparationCoches", "missions");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.MissionRetour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CeQueJaiAppris")
                        .HasColumnType("text");

                    b.Property<string>("CeQueJeVeuxAmeliorer")
                        .HasColumnType("text");

                    b.Property<string>("CeQuiAEteDifficile")
                        .HasColumnType("text");

                    b.Property<string>("CeQuiSestBienPasse")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MissionAcceptationId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MissionAcceptationId")
                        .IsUnique();

                    b.ToTable("MissionRetours", "missions");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.ParticulierProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ParticulierProfiles", "missions");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.MissionAcceptation", b =>
                {
                    b.HasOne("Spectrometre.Modules.Missions.Entities.Mission", "Mission")
                        .WithMany("Acceptations")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.MissionEvaluationParticulier", b =>
                {
                    b.HasOne("Spectrometre.Modules.Missions.Entities.MissionAcceptation", "MissionAcceptation")
                        .WithMany()
                        .HasForeignKey("MissionAcceptationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissionAcceptation");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.MissionPreparationCoche", b =>
                {
                    b.HasOne("Spectrometre.Modules.Missions.Entities.MissionAcceptation", "MissionAcceptation")
                        .WithMany()
                        .HasForeignKey("MissionAcceptationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissionAcceptation");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.MissionRetour", b =>
                {
                    b.HasOne("Spectrometre.Modules.Missions.Entities.MissionAcceptation", "MissionAcceptation")
                        .WithMany()
                        .HasForeignKey("MissionAcceptationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissionAcceptation");
                });

            modelBuilder.Entity("Spectrometre.Modules.Missions.Entities.Mission", b =>
                {
                    b.Navigation("Acceptations");
                });
#pragma warning restore 612, 618
        }
    }
}
