using System.Globalization;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Spectrometre.Modules.PostesRecrutement.Services;

/// <summary>Implémentation réelle de <see cref="IAnalysePdfService"/> — même pattern que <c>CvPdfService</c>.</summary>
public sealed class AnalysePdfService : IAnalysePdfService
{
    static AnalysePdfService()
    {
        // Licence Community — même choix que CvPdfService / mvp (PdfReportGenerator).
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GenerateAnalysePdf(AnalysePdfModel model)
    {
        var en = model.English;
        var culture = en ? CultureInfo.GetCultureInfo("en") : CultureInfo.GetCultureInfo("fr-FR");

        var title = en ? "AI compatibility analysis" : "Analyse IA de compatibilité";
        var labelPoste = en ? "Job title" : "Titre du poste";
        var labelCandidat = en ? "Candidate" : "Candidat";
        var labelScore = en ? "Compatibility score" : "Score de compatibilité";
        var labelGenereeLe = en ? "Generated on" : "Généré le";
        var labelSource = en ? "Source" : "Source";
        var sourceValue = model.GenereeParIa
            ? (en ? "Generated by AI" : "Généré par IA")
            : (en ? "Generated locally" : "Généré localement");
        var labelAnalyse = en ? "Analysis" : "Analyse";
        var scoreValue = model.ScoreCompatibilite is int s
            ? $"{s} %"
            : (en ? "n/a" : "n/d");
        var candidatValue = string.IsNullOrWhiteSpace(model.NomCandidat)
            ? $"#{model.CandidateProfileId}"
            : $"{model.NomCandidat.Trim()} (#{model.CandidateProfileId})";
        var genereeLeValue = model.GenereeLe.ToLocalTime().ToString("g", culture);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Text(title).FontSize(18).Bold();

                page.Content().PaddingTop(10).Column(column =>
                {
                    column.Spacing(12);

                    column.Item().Element(c => Section(c, en ? "Summary" : "Synthèse", section =>
                    {
                        Field(section, labelPoste, model.TitrePoste);
                        Field(section, labelCandidat, candidatValue);
                        Field(section, labelScore, scoreValue);
                        Field(section, labelGenereeLe, genereeLeValue);
                        Field(section, labelSource, sourceValue);
                    }));

                    column.Item().Element(c => Section(c, labelAnalyse, section =>
                    {
                        var texte = string.IsNullOrWhiteSpace(model.AnalyseTexte)
                            ? (en ? "(empty)" : "(vide)")
                            : model.AnalyseTexte.Trim();
                        section.Item().Text(texte);
                    }));
                });
            });
        });

        return document.GeneratePdf();
    }

    private static void Section(IContainer container, string title, Action<ColumnDescriptor> content)
    {
        container.Column(column =>
        {
            column.Item().Text(title).FontSize(13).Bold();
            column.Item().PaddingTop(4).Column(content);
        });
    }

    private static void Field(ColumnDescriptor section, string label, string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return;

        section.Item().Text(t =>
        {
            t.Span($"{label} : ").SemiBold();
            t.Span(value);
        });
    }
}
