// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.ProfilCandidat.Data;

#nullable disable

namespace Spectrometre.Modules.ProfilCandidat.Data.Migrations
{
    [DbContext(typeof(ProfilCandidatDbContext))]
    [Migration("20260806204058_AddQuestionTextEn")]
    partial class AddQuestionTextEn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profil_candidat")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId", "QuestionId")
                        .IsUnique();

                    b.ToTable("CandidateAnswers", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateCompatibilityCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("ComportementaleNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ComportementaleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CulturelleNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CulturelleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MotivationnelleNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("MotivationnelleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OrganisationnelleNotes")
                        .HasColumnType("text");

                    b.Property<string>("PointsVigilanceNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PointsVigilanceTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("RythmeTravail")
                        .HasColumnType("integer");

                    b.Property<string>("TechniqueNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("TechniqueTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CandidateCompatibilityCriteria", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextEn")
                        .HasColumnType("text");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("CandidateQuestions", "profil_candidat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1,
                            Text = "Quelles activités aimez-vous faire, même lorsqu'elles demandent des efforts ?",
                            TextEn = "What activities do you enjoy doing, even when they require effort?",
                            Theme = 0
                        },
                        new
                        {
                            Id = 2,
                            Number = 2,
                            Text = "Quelles tâches vous donnent de l'énergie au lieu de vous fatiguer rapidement ?",
                            TextEn = "Which tasks give you energy instead of quickly tiring you out?",
                            Theme = 0
                        },
                        new
                        {
                            Id = 3,
                            Number = 3,
                            Text = "Dans quelles activités perdez-vous parfois la notion du temps ?",
                            TextEn = "In which activities do you sometimes lose track of time?",
                            Theme = 0
                        },
                        new
                        {
                            Id = 4,
                            Number = 4,
                            Text = "Quels sujets, domaines ou problèmes attirent naturellement votre curiosité ?",
                            TextEn = "Which subjects, fields or problems naturally attract your curiosity?",
                            Theme = 0
                        },
                        new
                        {
                            Id = 5,
                            Number = 5,
                            Text = "Quelles choses apprenez-vous plus facilement que d'autres personnes ?",
                            TextEn = "What things do you learn more easily than other people?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 6,
                            Number = 6,
                            Text = "Pour quelles activités les autres vous demandent-ils souvent de l'aide ?",
                            TextEn = "What activities do others often ask you for help with?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 7,
                            Number = 7,
                            Text = "Quelles qualités reviennent souvent dans les compliments que l'on vous fait ?",
                            TextEn = "Which qualities come up often in the compliments people give you?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 8,
                            Number = 8,
                            Text = "Quels talents utilisez-vous spontanément, sans toujours les considérer comme importants ?",
                            TextEn = "Which talents do you use spontaneously, without always considering them important?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 9,
                            Number = 9,
                            Text = "Quelles compétences avez-vous acquises par les études ?",
                            TextEn = "What skills have you acquired through your studies?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 10,
                            Number = 10,
                            Text = "Quelles compétences avez-vous acquises par les stages, emplois ou expériences pratiques ?",
                            TextEn = "What skills have you acquired through internships, jobs or hands-on experience?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 11,
                            Number = 11,
                            Text = "Quelles compétences avez-vous acquises dans la famille, la communauté, les loisirs ou le bénévolat ?",
                            TextEn = "What skills have you acquired within your family, community, hobbies or volunteer work?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 12,
                            Number = 12,
                            Text = "Quelles compétences souhaitez-vous encore développer ?",
                            TextEn = "What skills would you still like to develop?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 13,
                            Number = 13,
                            Text = "Qu'est-ce qui est le plus important pour vous dans un travail ?",
                            TextEn = "What matters most to you in a job?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 14,
                            Number = 14,
                            Text = "Quelles causes, missions ou types de problèmes aimeriez-vous contribuer à résoudre ?",
                            TextEn = "What causes, missions or types of problems would you like to help solve?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 15,
                            Number = 15,
                            Text = "Quel type de reconnaissance vous motive le plus ?",
                            TextEn = "What type of recognition motivates you the most?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 16,
                            Number = 16,
                            Text = "Préférez-vous travailler seul, en équipe ou dans un mélange des deux ?",
                            TextEn = "Do you prefer working alone, as part of a team, or a mix of both?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 17,
                            Number = 17,
                            Text = "Préférez-vous un travail très structuré ou un travail qui laisse de la liberté d'organisation ?",
                            TextEn = "Do you prefer a highly structured job or one that leaves room for organizing your own work?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 18,
                            Number = 18,
                            Text = "Préférez-vous un environnement calme, dynamique, compétitif, créatif, social, technique ou administratif ?",
                            TextEn = "Do you prefer a calm, dynamic, competitive, creative, social, technical or administrative environment?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 19,
                            Number = 19,
                            Text = "Quel rythme de travail vous convient le mieux ?",
                            TextEn = "What work pace suits you best?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 20,
                            Number = 20,
                            Text = "Quels types de tâches évitez-vous ou vous épuisent rapidement ?",
                            TextEn = "What types of tasks do you avoid or that quickly exhaust you?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 21,
                            Number = 21,
                            Text = "Quelles conditions de travail vous stressent fortement ?",
                            TextEn = "What working conditions stress you out the most?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 22,
                            Number = 22,
                            Text = "Quels comportements ou styles de gestion vous démotivent ?",
                            TextEn = "What behaviors or management styles demotivate you?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 23,
                            Number = 23,
                            Text = "Quels domaines ou postes vous intéressent, mais pourraient ne pas correspondre à votre personnalité ?",
                            TextEn = "What fields or positions interest you, but might not match your personality?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 24,
                            Number = 24,
                            Text = "Quelles activités ou situations vous placent dans un état d'esprit de réalisation, d'acceptation, d'accommodation, de collaboration, d'opposition, de contrainte ou de frustration ?",
                            TextEn = "What activities or situations put you in a mindset of accomplishment, acceptance, accommodation, collaboration, opposition, constraint or frustration?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 25,
                            Number = 25,
                            Text = "Quelles situations ou activités provoquent chez vous des émotions de joie, de colère ou de peine/tristesse ?",
                            TextEn = "What situations or activities trigger feelings of joy, anger or sadness in you?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 26,
                            Number = 26,
                            Text = "Quelles activités ou situations vous procurent des sentiments de satisfaction ou d'insatisfaction ?",
                            TextEn = "What activities or situations give you feelings of satisfaction or dissatisfaction?",
                            Theme = 5
                        });
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestionExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("CandidateQuestionExamples", "profil_candidat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            QuestionId = 1,
                            Text = "J'aime organiser des activités, même si cela demande beaucoup de préparation.",
                            TextEn = "I enjoy organizing activities, even when they require a lot of preparation."
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            QuestionId = 1,
                            Text = "J'aime réparer des objets, chercher la panne et trouver une solution.",
                            TextEn = "I enjoy fixing things, diagnosing the problem and finding a solution."
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            QuestionId = 1,
                            Text = "J'aime expliquer quelque chose à une autre personne jusqu'à ce qu'elle comprenne.",
                            TextEn = "I enjoy explaining something to someone until they understand it."
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 3,
                            QuestionId = 1,
                            Text = "J'aime écrire, lire, analyser ou résumer des informations.",
                            TextEn = "I enjoy writing, reading, analyzing or summarizing information."
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 4,
                            QuestionId = 1,
                            Text = "J'aime vendre, négocier ou convaincre une personne d'adhérer à une idée.",
                            TextEn = "I enjoy selling, negotiating or convincing someone to embrace an idea."
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 0,
                            QuestionId = 2,
                            Text = "Travailler avec des enfants, des jeunes ou des personnes en difficulté.",
                            TextEn = "Working with children, young people or people in difficulty."
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            QuestionId = 2,
                            Text = "Résoudre des problèmes techniques ou pratiques.",
                            TextEn = "Solving technical or practical problems."
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 2,
                            QuestionId = 2,
                            Text = "Créer des affiches, des contenus, des plans ou des présentations.",
                            TextEn = "Creating posters, content, plans or presentations."
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 3,
                            QuestionId = 2,
                            Text = "Accueillir des clients et répondre à leurs besoins.",
                            TextEn = "Welcoming clients and meeting their needs."
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 4,
                            QuestionId = 2,
                            Text = "Coordonner une équipe ou répartir les tâches.",
                            TextEn = "Coordinating a team or distributing tasks."
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 0,
                            QuestionId = 3,
                            Text = "Lorsque je dessine, crée, bricole ou conçois quelque chose.",
                            TextEn = "When I draw, create, tinker or design something."
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 1,
                            QuestionId = 3,
                            Text = "Lorsque j'effectue des recherches sur Internet pour comprendre un sujet.",
                            TextEn = "When I research a topic online to understand it."
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 2,
                            QuestionId = 3,
                            Text = "Lorsque je cuisine, jardine ou réalise une activité manuelle.",
                            TextEn = "When I cook, garden or do a hands-on activity."
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 3,
                            QuestionId = 3,
                            Text = "Lorsque je programme, calcule ou travaille sur un problème logique.",
                            TextEn = "When I code, calculate or work on a logical problem."
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 4,
                            QuestionId = 3,
                            Text = "Lorsque je discute avec quelqu'un pour l'écouter ou le conseiller.",
                            TextEn = "When I talk with someone to listen to them or offer advice."
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 0,
                            QuestionId = 4,
                            Text = "La santé, le bien-être et l'aide aux personnes.",
                            TextEn = "Health, well-being and helping people."
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 1,
                            QuestionId = 4,
                            Text = "Les machines, l'électricité, l'informatique ou la technologie.",
                            TextEn = "Machines, electricity, computing or technology."
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 2,
                            QuestionId = 4,
                            Text = "L'éducation, la psychologie, la communication ou les relations humaines.",
                            TextEn = "Education, psychology, communication or human relations."
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 3,
                            QuestionId = 4,
                            Text = "Le commerce, l'entrepreneuriat, la gestion ou l'argent.",
                            TextEn = "Business, entrepreneurship, management or money."
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 4,
                            QuestionId = 4,
                            Text = "L'environnement, l'agriculture, l'alimentation ou le développement durable.",
                            TextEn = "The environment, agriculture, food or sustainable development."
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 0,
                            QuestionId = 5,
                            Text = "J'apprends facilement les langues.",
                            TextEn = "I learn languages easily."
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 1,
                            QuestionId = 5,
                            Text = "Je comprends vite les chiffres, les calculs ou les tableaux.",
                            TextEn = "I quickly understand numbers, calculations or tables."
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 2,
                            QuestionId = 5,
                            Text = "Je retiens facilement les consignes pratiques.",
                            TextEn = "I easily remember practical instructions."
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 3,
                            QuestionId = 5,
                            Text = "Je comprends rapidement le fonctionnement des appareils ou des outils.",
                            TextEn = "I quickly understand how devices or tools work."
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 4,
                            QuestionId = 5,
                            Text = "J'apprends facilement en observant les autres faire.",
                            TextEn = "I learn easily by watching others do it."
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 0,
                            QuestionId = 6,
                            Text = "Pour rédiger un texte, corriger un document ou préparer une présentation.",
                            TextEn = "To write a text, proofread a document or prepare a presentation."
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 1,
                            QuestionId = 6,
                            Text = "Pour réparer un téléphone, un appareil ou résoudre un problème informatique.",
                            TextEn = "To fix a phone, a device or solve a computer problem."
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 2,
                            QuestionId = 6,
                            Text = "Pour organiser une fête, une réunion ou une activité.",
                            TextEn = "To organize a party, a meeting or an activity."
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 3,
                            QuestionId = 6,
                            Text = "Pour expliquer une leçon, un devoir ou une procédure.",
                            TextEn = "To explain a lesson, an assignment or a procedure."
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 4,
                            QuestionId = 6,
                            Text = "Pour écouter un problème personnel et prodiguer un conseil.",
                            TextEn = "To listen to a personal problem and give advice."
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 0,
                            QuestionId = 7,
                            Text = "On me dit souvent que je suis patient.",
                            TextEn = "I'm often told I'm patient."
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 1,
                            QuestionId = 7,
                            Text = "On me dit que je suis sérieux et fiable.",
                            TextEn = "I'm told I'm serious and reliable."
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 2,
                            QuestionId = 7,
                            Text = "On me reconnaît comme quelqu'un de créatif.",
                            TextEn = "I'm recognized as someone creative."
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 3,
                            QuestionId = 7,
                            Text = "On dit que je communique facilement avec les autres.",
                            TextEn = "People say I communicate easily with others."
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 4,
                            QuestionId = 7,
                            Text = "On me dit que je suis courageux et persévérant.",
                            TextEn = "I'm told I'm courageous and persistent."
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 0,
                            QuestionId = 8,
                            Text = "Je remarque rapidement lorsqu'une personne ne va pas bien.",
                            TextEn = "I quickly notice when someone isn't doing well."
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 1,
                            QuestionId = 8,
                            Text = "Je trouve facilement des solutions simples à des problèmes pratiques.",
                            TextEn = "I easily find simple solutions to practical problems."
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 2,
                            QuestionId = 8,
                            Text = "Je mets de l'ordre dans les choses sans qu'on me le demande.",
                            TextEn = "I organize things without being asked to."
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 3,
                            QuestionId = 8,
                            Text = "Je motive les autres lorsqu'ils se découragent.",
                            TextEn = "I motivate others when they become discouraged."
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 4,
                            QuestionId = 8,
                            Text = "Je mémorise facilement les détails importants.",
                            TextEn = "I easily remember important details."
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 0,
                            QuestionId = 9,
                            Text = "Lire, comprendre et résumer un texte.",
                            TextEn = "Reading, understanding and summarizing a text."
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 1,
                            QuestionId = 9,
                            Text = "Utiliser un ordinateur, un logiciel de traitement de texte ou un tableur.",
                            TextEn = "Using a computer, word processing software or a spreadsheet."
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 2,
                            QuestionId = 9,
                            Text = "Faire des calculs, gérer des données ou interpréter des résultats.",
                            TextEn = "Doing calculations, managing data or interpreting results."
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 3,
                            QuestionId = 9,
                            Text = "Présenter un exposé devant un groupe.",
                            TextEn = "Giving a presentation in front of a group."
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 4,
                            QuestionId = 9,
                            Text = "Comprendre les bases d'un domaine comme la comptabilité, l'électricité, la mécanique, la santé, l'enseignement.",
                            TextEn = "Understanding the basics of a field such as accounting, electricity, mechanics, health or teaching."
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 0,
                            QuestionId = 10,
                            Text = "Accueillir des clients et répondre à leurs demandes.",
                            TextEn = "Welcoming clients and responding to their requests."
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 1,
                            QuestionId = 10,
                            Text = "Respecter des horaires et des consignes de travail.",
                            TextEn = "Respecting schedules and work instructions."
                        },
                        new
                        {
                            Id = 48,
                            DisplayOrder = 2,
                            QuestionId = 10,
                            Text = "Travailler en équipe avec des collègues.",
                            TextEn = "Working as part of a team with colleagues."
                        },
                        new
                        {
                            Id = 49,
                            DisplayOrder = 3,
                            QuestionId = 10,
                            Text = "Utiliser des outils, machines, logiciels ou équipements professionnels.",
                            TextEn = "Using professional tools, machines, software or equipment."
                        },
                        new
                        {
                            Id = 50,
                            DisplayOrder = 4,
                            QuestionId = 10,
                            Text = "Gérer une petite caisse, un stock, une commande ou un planning.",
                            TextEn = "Managing petty cash, inventory, an order or a schedule."
                        },
                        new
                        {
                            Id = 51,
                            DisplayOrder = 0,
                            QuestionId = 11,
                            Text = "Encadrer des enfants ou des jeunes.",
                            TextEn = "Supervising children or young people."
                        },
                        new
                        {
                            Id = 52,
                            DisplayOrder = 1,
                            QuestionId = 11,
                            Text = "Préparer des repas, organiser une activité ou gérer une petite équipe.",
                            TextEn = "Preparing meals, organizing an activity or managing a small team."
                        },
                        new
                        {
                            Id = 53,
                            DisplayOrder = 2,
                            QuestionId = 11,
                            Text = "Participer à des actions communautaires, religieuses, sportives ou sociales.",
                            TextEn = "Taking part in community, religious, sports or social activities."
                        },
                        new
                        {
                            Id = 54,
                            DisplayOrder = 3,
                            QuestionId = 11,
                            Text = "Prendre soin d'une personne âgée, malade ou vulnérable.",
                            TextEn = "Caring for an elderly, sick or vulnerable person."
                        },
                        new
                        {
                            Id = 55,
                            DisplayOrder = 4,
                            QuestionId = 11,
                            Text = "Gérer un petit commerce familial ou aider dans une activité agricole.",
                            TextEn = "Managing a small family business or helping with farm work."
                        },
                        new
                        {
                            Id = 56,
                            DisplayOrder = 0,
                            QuestionId = 12,
                            Text = "Améliorer mon expression orale.",
                            TextEn = "Improving my spoken communication."
                        },
                        new
                        {
                            Id = 57,
                            DisplayOrder = 1,
                            QuestionId = 12,
                            Text = "Apprendre une langue étrangère.",
                            TextEn = "Learning a foreign language."
                        },
                        new
                        {
                            Id = 58,
                            DisplayOrder = 2,
                            QuestionId = 12,
                            Text = "Maîtriser davantage l'informatique.",
                            TextEn = "Becoming more proficient with computers."
                        },
                        new
                        {
                            Id = 59,
                            DisplayOrder = 3,
                            QuestionId = 12,
                            Text = "Développer mes compétences en gestion ou en comptabilité.",
                            TextEn = "Developing my management or accounting skills."
                        },
                        new
                        {
                            Id = 60,
                            DisplayOrder = 4,
                            QuestionId = 12,
                            Text = "Apprendre à mieux gérer le stress et les priorités.",
                            TextEn = "Learning to better manage stress and priorities."
                        },
                        new
                        {
                            Id = 61,
                            DisplayOrder = 0,
                            QuestionId = 13,
                            Text = "Avoir un travail stable et sécurisant.",
                            TextEn = "Having a stable, secure job."
                        },
                        new
                        {
                            Id = 62,
                            DisplayOrder = 1,
                            QuestionId = 13,
                            Text = "Aider les autres et me sentir utile.",
                            TextEn = "Helping others and feeling useful."
                        },
                        new
                        {
                            Id = 63,
                            DisplayOrder = 2,
                            QuestionId = 13,
                            Text = "Avoir un bon revenu pour soutenir ma famille.",
                            TextEn = "Having a good income to support my family."
                        },
                        new
                        {
                            Id = 64,
                            DisplayOrder = 3,
                            QuestionId = 13,
                            Text = "Apprendre constamment et progresser.",
                            TextEn = "Constantly learning and progressing."
                        },
                        new
                        {
                            Id = 65,
                            DisplayOrder = 4,
                            QuestionId = 13,
                            Text = "Avoir de l'autonomie et pouvoir prendre des initiatives.",
                            TextEn = "Having autonomy and being able to take initiative."
                        },
                        new
                        {
                            Id = 66,
                            DisplayOrder = 5,
                            QuestionId = 13,
                            Text = "Travailler dans un environnement respectueux.",
                            TextEn = "Working in a respectful environment."
                        },
                        new
                        {
                            Id = 67,
                            DisplayOrder = 0,
                            QuestionId = 14,
                            Text = "L'éducation des enfants et des jeunes.",
                            TextEn = "The education of children and young people."
                        },
                        new
                        {
                            Id = 68,
                            DisplayOrder = 1,
                            QuestionId = 14,
                            Text = "L'accès aux soins de santé.",
                            TextEn = "Access to healthcare."
                        },
                        new
                        {
                            Id = 69,
                            DisplayOrder = 2,
                            QuestionId = 14,
                            Text = "La pauvreté, le chômage ou l'exclusion sociale.",
                            TextEn = "Poverty, unemployment or social exclusion."
                        },
                        new
                        {
                            Id = 70,
                            DisplayOrder = 3,
                            QuestionId = 14,
                            Text = "La protection de l'environnement.",
                            TextEn = "Environmental protection."
                        },
                        new
                        {
                            Id = 71,
                            DisplayOrder = 4,
                            QuestionId = 14,
                            Text = "L'amélioration du service aux clients.",
                            TextEn = "Improving customer service."
                        },
                        new
                        {
                            Id = 72,
                            DisplayOrder = 5,
                            QuestionId = 14,
                            Text = "La sécurité, l'ordre ou la bonne organisation dans une entreprise.",
                            TextEn = "Safety, order or good organization within a company."
                        },
                        new
                        {
                            Id = 73,
                            DisplayOrder = 0,
                            QuestionId = 15,
                            Text = "Être encouragé verbalement lorsque j'effectue bien mon travail.",
                            TextEn = "Being verbally encouraged when I do my job well."
                        },
                        new
                        {
                            Id = 74,
                            DisplayOrder = 1,
                            QuestionId = 15,
                            Text = "Recevoir plus de responsabilités.",
                            TextEn = "Receiving more responsibilities."
                        },
                        new
                        {
                            Id = 75,
                            DisplayOrder = 2,
                            QuestionId = 15,
                            Text = "Voir concrètement les résultats de mes efforts.",
                            TextEn = "Concretely seeing the results of my efforts."
                        },
                        new
                        {
                            Id = 76,
                            DisplayOrder = 3,
                            QuestionId = 15,
                            Text = "Progresser vers un meilleur poste.",
                            TextEn = "Advancing toward a better position."
                        },
                        new
                        {
                            Id = 77,
                            DisplayOrder = 4,
                            QuestionId = 15,
                            Text = "Sentir que je contribue à la réussite d'une équipe.",
                            TextEn = "Feeling that I contribute to a team's success."
                        },
                        new
                        {
                            Id = 78,
                            DisplayOrder = 5,
                            QuestionId = 15,
                            Text = "Recevoir une rémunération juste pour le travail accompli.",
                            TextEn = "Receiving fair pay for the work accomplished."
                        },
                        new
                        {
                            Id = 79,
                            DisplayOrder = 0,
                            QuestionId = 16,
                            Text = "Je préfère travailler en équipe, car j'aime échanger avec les autres.",
                            TextEn = "I prefer working as part of a team, because I enjoy exchanging with others."
                        },
                        new
                        {
                            Id = 80,
                            DisplayOrder = 1,
                            QuestionId = 16,
                            Text = "Je préfère travailler seul lorsque je dois me concentrer.",
                            TextEn = "I prefer working alone when I need to concentrate."
                        },
                        new
                        {
                            Id = 81,
                            DisplayOrder = 2,
                            QuestionId = 16,
                            Text = "J'aime un mélange des deux : travailler seul pour avancer, puis échanger avec l'équipe.",
                            TextEn = "I like a mix of both: working alone to make progress, then discussing with the team."
                        },
                        new
                        {
                            Id = 82,
                            DisplayOrder = 3,
                            QuestionId = 16,
                            Text = "Je suis plus efficace lorsque les rôles de chacun sont bien définis.",
                            TextEn = "I'm more effective when everyone's roles are clearly defined."
                        },
                        new
                        {
                            Id = 83,
                            DisplayOrder = 4,
                            QuestionId = 16,
                            Text = "Je préfère un environnement où l'on s'entraide.",
                            TextEn = "I prefer an environment where people help each other."
                        },
                        new
                        {
                            Id = 84,
                            DisplayOrder = 0,
                            QuestionId = 17,
                            Text = "Je préfère un travail structuré avec des consignes claires.",
                            TextEn = "I prefer structured work with clear instructions."
                        },
                        new
                        {
                            Id = 85,
                            DisplayOrder = 1,
                            QuestionId = 17,
                            Text = "J'aime avoir une certaine liberté pour organiser ma journée.",
                            TextEn = "I like having some freedom to organize my day."
                        },
                        new
                        {
                            Id = 86,
                            DisplayOrder = 2,
                            QuestionId = 17,
                            Text = "Je suis à l'aise lorsque les objectifs sont clairs, même si la méthode reste flexible.",
                            TextEn = "I'm comfortable when the goals are clear, even if the method stays flexible."
                        },
                        new
                        {
                            Id = 87,
                            DisplayOrder = 3,
                            QuestionId = 17,
                            Text = "J'ai besoin d'un cadre précis pour éviter la confusion.",
                            TextEn = "I need a precise framework to avoid confusion."
                        },
                        new
                        {
                            Id = 88,
                            DisplayOrder = 4,
                            QuestionId = 17,
                            Text = "Je préfère les environnements où l'on peut proposer des idées nouvelles.",
                            TextEn = "I prefer environments where new ideas can be proposed."
                        },
                        new
                        {
                            Id = 89,
                            DisplayOrder = 0,
                            QuestionId = 18,
                            Text = "Je préfère un environnement calme et organisé.",
                            TextEn = "I prefer a calm, organized environment."
                        },
                        new
                        {
                            Id = 90,
                            DisplayOrder = 1,
                            QuestionId = 18,
                            Text = "Je suis motivé par un environnement dynamique avec beaucoup d'activités.",
                            TextEn = "I'm motivated by a dynamic environment with lots of activity."
                        },
                        new
                        {
                            Id = 91,
                            DisplayOrder = 2,
                            QuestionId = 18,
                            Text = "J'aime les milieux sociaux où l'on rencontre beaucoup de personnes.",
                            TextEn = "I enjoy social settings where I meet lots of people."
                        },
                        new
                        {
                            Id = 92,
                            DisplayOrder = 3,
                            QuestionId = 18,
                            Text = "Je préfère un environnement technique où l'on résout des problèmes concrets.",
                            TextEn = "I prefer a technical environment where concrete problems get solved."
                        },
                        new
                        {
                            Id = 93,
                            DisplayOrder = 4,
                            QuestionId = 18,
                            Text = "Je suis à l'aise dans un cadre administratif avec des documents, des dossiers et des procédures.",
                            TextEn = "I'm comfortable in an administrative setting with documents, files and procedures."
                        },
                        new
                        {
                            Id = 94,
                            DisplayOrder = 5,
                            QuestionId = 18,
                            Text = "J'aime les environnements créatifs où l'on peut imaginer et construire quelque chose de nouveau.",
                            TextEn = "I enjoy creative environments where you can imagine and build something new."
                        },
                        new
                        {
                            Id = 95,
                            DisplayOrder = 0,
                            QuestionId = 19,
                            Text = "Un rythme régulier avec des horaires stables.",
                            TextEn = "A steady pace with stable hours."
                        },
                        new
                        {
                            Id = 96,
                            DisplayOrder = 1,
                            QuestionId = 19,
                            Text = "Un rythme rapide avec des défis quotidiens.",
                            TextEn = "A fast pace with daily challenges."
                        },
                        new
                        {
                            Id = 97,
                            DisplayOrder = 2,
                            QuestionId = 19,
                            Text = "Un rythme flexible qui me permet de m'organiser.",
                            TextEn = "A flexible pace that lets me organize myself."
                        },
                        new
                        {
                            Id = 98,
                            DisplayOrder = 3,
                            QuestionId = 19,
                            Text = "Un travail avec déplacements, car j'aime bouger.",
                            TextEn = "A job involving travel, because I like moving around."
                        },
                        new
                        {
                            Id = 99,
                            DisplayOrder = 4,
                            QuestionId = 19,
                            Text = "Un travail sans déplacements fréquents, car je préfère rester dans un même lieu.",
                            TextEn = "A job without frequent travel, because I prefer staying in one place."
                        },
                        new
                        {
                            Id = 100,
                            DisplayOrder = 5,
                            QuestionId = 19,
                            Text = "Un rythme saisonnier ou variable, si les périodes chargées sont bien organisées.",
                            TextEn = "A seasonal or variable pace, as long as busy periods are well organized."
                        },
                        new
                        {
                            Id = 101,
                            DisplayOrder = 0,
                            QuestionId = 20,
                            Text = "Les tâches très répétitives sans variation.",
                            TextEn = "Highly repetitive tasks with no variation."
                        },
                        new
                        {
                            Id = 102,
                            DisplayOrder = 1,
                            QuestionId = 20,
                            Text = "Les tâches qui demandent de parler constamment en public.",
                            TextEn = "Tasks that require constantly speaking in public."
                        },
                        new
                        {
                            Id = 103,
                            DisplayOrder = 2,
                            QuestionId = 20,
                            Text = "Les travaux physiques très lourds.",
                            TextEn = "Very heavy physical labor."
                        },
                        new
                        {
                            Id = 104,
                            DisplayOrder = 3,
                            QuestionId = 20,
                            Text = "Les tâches administratives longues et sans contact humain.",
                            TextEn = "Long administrative tasks with no human contact."
                        },
                        new
                        {
                            Id = 105,
                            DisplayOrder = 4,
                            QuestionId = 20,
                            Text = "Les activités sans objectifs clairs.",
                            TextEn = "Activities without clear objectives."
                        },
                        new
                        {
                            Id = 106,
                            DisplayOrder = 5,
                            QuestionId = 20,
                            Text = "Les tâches où je dois agir trop vite sans comprendre ce qu'on attend de moi.",
                            TextEn = "Tasks where I have to act too quickly without understanding what's expected of me."
                        },
                        new
                        {
                            Id = 107,
                            DisplayOrder = 0,
                            QuestionId = 21,
                            Text = "Les changements de dernière minute sans explication.",
                            TextEn = "Last-minute changes without explanation."
                        },
                        new
                        {
                            Id = 108,
                            DisplayOrder = 1,
                            QuestionId = 21,
                            Text = "Le manque de respect ou les conflits fréquents.",
                            TextEn = "Lack of respect or frequent conflicts."
                        },
                        new
                        {
                            Id = 109,
                            DisplayOrder = 2,
                            QuestionId = 21,
                            Text = "Les délais trop courts et mal organisés.",
                            TextEn = "Deadlines that are too short and poorly organized."
                        },
                        new
                        {
                            Id = 110,
                            DisplayOrder = 3,
                            QuestionId = 21,
                            Text = "Le bruit permanent ou l'agitation excessive.",
                            TextEn = "Constant noise or excessive commotion."
                        },
                        new
                        {
                            Id = 111,
                            DisplayOrder = 4,
                            QuestionId = 21,
                            Text = "Le manque de matériel pour bien effectuer le travail.",
                            TextEn = "Lack of equipment to do the job properly."
                        },
                        new
                        {
                            Id = 112,
                            DisplayOrder = 5,
                            QuestionId = 21,
                            Text = "L'absence de soutien lorsqu'il y a des difficultés.",
                            TextEn = "Lack of support when difficulties arise."
                        },
                        new
                        {
                            Id = 113,
                            DisplayOrder = 0,
                            QuestionId = 22,
                            Text = "Les critiques humiliantes ou publiques.",
                            TextEn = "Humiliating or public criticism."
                        },
                        new
                        {
                            Id = 114,
                            DisplayOrder = 1,
                            QuestionId = 22,
                            Text = "Le favoritisme.",
                            TextEn = "Favoritism."
                        },
                        new
                        {
                            Id = 115,
                            DisplayOrder = 2,
                            QuestionId = 22,
                            Text = "Le manque de communication.",
                            TextEn = "Lack of communication."
                        },
                        new
                        {
                            Id = 116,
                            DisplayOrder = 3,
                            QuestionId = 22,
                            Text = "Les ordres contradictoires.",
                            TextEn = "Contradictory orders."
                        },
                        new
                        {
                            Id = 117,
                            DisplayOrder = 4,
                            QuestionId = 22,
                            Text = "L'absence de reconnaissance.",
                            TextEn = "Lack of recognition."
                        },
                        new
                        {
                            Id = 118,
                            DisplayOrder = 5,
                            QuestionId = 22,
                            Text = "Le contrôle excessif sans confiance.",
                            TextEn = "Excessive control without trust."
                        },
                        new
                        {
                            Id = 119,
                            DisplayOrder = 0,
                            QuestionId = 23,
                            Text = "La vente m'intéresse, mais je ne suis pas encore à l'aise avec la pression des objectifs.",
                            TextEn = "Sales interests me, but I'm not yet comfortable with the pressure of targets."
                        },
                        new
                        {
                            Id = 120,
                            DisplayOrder = 1,
                            QuestionId = 23,
                            Text = "Le travail médical m'attire, mais je dois réfléchir à ma capacité à gérer la souffrance.",
                            TextEn = "Medical work attracts me, but I need to think about my ability to cope with suffering."
                        },
                        new
                        {
                            Id = 121,
                            DisplayOrder = 2,
                            QuestionId = 23,
                            Text = "La gestion d'équipe m'intéresse, mais je dois développer mon autorité et ma communication.",
                            TextEn = "Team management interests me, but I need to develop my authority and communication."
                        },
                        new
                        {
                            Id = 122,
                            DisplayOrder = 3,
                            QuestionId = 23,
                            Text = "L'entrepreneuriat m'attire, mais je dois mieux comprendre les risques financiers.",
                            TextEn = "Entrepreneurship attracts me, but I need to better understand the financial risks."
                        },
                        new
                        {
                            Id = 123,
                            DisplayOrder = 4,
                            QuestionId = 23,
                            Text = "L'informatique m'intéresse, mais je dois vérifier si j'aime vraiment travailler longtemps seul devant un écran.",
                            TextEn = "IT interests me, but I need to check whether I really enjoy working alone in front of a screen for long stretches."
                        },
                        new
                        {
                            Id = 124,
                            DisplayOrder = 0,
                            QuestionId = 24,
                            Text = "Je me sens en réalisation lorsque je termine une tâche utile ou visible.",
                            TextEn = "I feel a sense of accomplishment when I finish a useful or visible task."
                        },
                        new
                        {
                            Id = 125,
                            DisplayOrder = 1,
                            QuestionId = 24,
                            Text = "Je me sens en collaboration lorsque les rôles sont clairs et que chacun respecte l'autre.",
                            TextEn = "I feel a sense of collaboration when roles are clear and everyone respects each other."
                        },
                        new
                        {
                            Id = 126,
                            DisplayOrder = 2,
                            QuestionId = 24,
                            Text = "Je ressens de la frustration lorsque je dois travailler sans explication, sans moyens suffisants ou dans un climat de tension.",
                            TextEn = "I feel frustrated when I have to work without explanation, without sufficient resources, or in a tense atmosphere."
                        },
                        new
                        {
                            Id = 127,
                            DisplayOrder = 0,
                            QuestionId = 25,
                            Text = "Je ressens de la joie lorsque mon travail aide quelqu'un ou produit un résultat concret.",
                            TextEn = "I feel joy when my work helps someone or produces a concrete result."
                        },
                        new
                        {
                            Id = 128,
                            DisplayOrder = 1,
                            QuestionId = 25,
                            Text = "Je ressens de la colère face à l'injustice ou au manque de respect.",
                            TextEn = "I feel anger in the face of injustice or lack of respect."
                        },
                        new
                        {
                            Id = 129,
                            DisplayOrder = 2,
                            QuestionId = 25,
                            Text = "Je ressens de la tristesse lorsque mes efforts ne sont pas reconnus.",
                            TextEn = "I feel sad when my efforts aren't recognized."
                        },
                        new
                        {
                            Id = 130,
                            DisplayOrder = 0,
                            QuestionId = 26,
                            Text = "Je ressens de la satisfaction quand mon travail a du sens et un résultat visible.",
                            TextEn = "I feel satisfied when my work is meaningful and has a visible result."
                        },
                        new
                        {
                            Id = 131,
                            DisplayOrder = 1,
                            QuestionId = 26,
                            Text = "Je ressens de l'insatisfaction lorsque mes efforts ne sont pas reconnus ou lorsque mes tâches n'ont pas de sens pour moi.",
                            TextEn = "I feel dissatisfied when my efforts aren't recognized or when my tasks don't feel meaningful to me."
                        });
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateSynthesisTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CandidateSynthesisTags", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvCaracteristiquesPersonnelles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AptitudesProfessionnelles")
                        .HasColumnType("text");

                    b.Property<string>("AttitudesRelationnelles")
                        .HasColumnType("text");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("CapaciteSousPression")
                        .HasColumnType("text");

                    b.Property<string>("DisponibiliteMobilite")
                        .HasColumnType("text");

                    b.Property<string>("QualitesPersonnelles")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvCaracteristiquesPersonnelles", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvCompetencesEtudes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("CompetencesTechniques")
                        .HasColumnType("text");

                    b.Property<string>("ConnaissancesTheoriques")
                        .HasColumnType("text");

                    b.Property<string>("LanguesMaitrisees")
                        .HasColumnType("text");

                    b.Property<string>("OutilsLogicielsMethodes")
                        .HasColumnType("text");

                    b.Property<string>("SpecialitePrincipale")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvCompetencesEtudes", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvCoordonnees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseComplete")
                        .HasColumnType("text");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LieuNaissance")
                        .HasColumnType("text");

                    b.Property<string>("Nationalite")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Prenoms")
                        .HasColumnType("text");

                    b.Property<string>("ProfilOuPosteRecherche")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvCoordonnees", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<bool>("CertificationExactitude")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsentementConsultation")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("NomSignataire")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvDeclarations", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("CompetencesDeveloppees")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("EntrepriseOrganisationOuStage")
                        .HasColumnType("text");

                    b.Property<string>("FonctionOuActiviteExercee")
                        .HasColumnType("text");

                    b.Property<string>("Periode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CvExperiences", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvFormation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("DiplomeCertificatOuNiveau")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DomaineEtudes")
                        .HasColumnType("text");

                    b.Property<string>("Etablissement")
                        .HasColumnType("text");

                    b.Property<string>("Periode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CvFormations", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvLoisirs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivitesSportivesCulturelles")
                        .HasColumnType("text");

                    b.Property<string>("AutresCentresInteret")
                        .HasColumnType("text");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("EngagementsAssociatifs")
                        .HasColumnType("text");

                    b.Property<string>("LoisirsPreferes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvLoisirs", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("EntrepriseOrganisation")
                        .HasColumnType("text");

                    b.Property<string>("Fonction")
                        .HasColumnType("text");

                    b.Property<string>("LienAvecPostulant")
                        .HasColumnType("text");

                    b.Property<string>("NomPrenom")
                        .HasColumnType("text");

                    b.Property<string>("TelephoneOuEmail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CvReferences", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestionExample", b =>
                {
                    b.HasOne("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestion", null)
                        .WithMany("Examples")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestion", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
