// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.ProfilCandidat.Data;

#nullable disable

namespace Spectrometre.Modules.ProfilCandidat.Data.Migrations
{
    [DbContext(typeof(ProfilCandidatDbContext))]
    [Migration("20260806134237_AddCvForm")]
    partial class AddCvForm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profil_candidat")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId", "QuestionId")
                        .IsUnique();

                    b.ToTable("CandidateAnswers", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateCompatibilityCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("ComportementaleNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ComportementaleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CulturelleNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CulturelleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MotivationnelleNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("MotivationnelleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OrganisationnelleNotes")
                        .HasColumnType("text");

                    b.Property<string>("PointsVigilanceNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PointsVigilanceTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("RythmeTravail")
                        .HasColumnType("integer");

                    b.Property<string>("TechniqueNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("TechniqueTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CandidateCompatibilityCriteria", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("CandidateQuestions", "profil_candidat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1,
                            Text = "Quelles activités aimez-vous faire, même lorsqu'elles demandent des efforts ?",
                            Theme = 0
                        },
                        new
                        {
                            Id = 2,
                            Number = 2,
                            Text = "Quelles tâches vous donnent de l'énergie au lieu de vous fatiguer rapidement ?",
                            Theme = 0
                        },
                        new
                        {
                            Id = 3,
                            Number = 3,
                            Text = "Dans quelles activités perdez-vous parfois la notion du temps ?",
                            Theme = 0
                        },
                        new
                        {
                            Id = 4,
                            Number = 4,
                            Text = "Quels sujets, domaines ou problèmes attirent naturellement votre curiosité ?",
                            Theme = 0
                        },
                        new
                        {
                            Id = 5,
                            Number = 5,
                            Text = "Quelles choses apprenez-vous plus facilement que d'autres personnes ?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 6,
                            Number = 6,
                            Text = "Pour quelles activités les autres vous demandent-ils souvent de l'aide ?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 7,
                            Number = 7,
                            Text = "Quelles qualités reviennent souvent dans les compliments que l'on vous fait ?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 8,
                            Number = 8,
                            Text = "Quels talents utilisez-vous spontanément, sans toujours les considérer comme importants ?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 9,
                            Number = 9,
                            Text = "Quelles compétences avez-vous acquises par les études ?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 10,
                            Number = 10,
                            Text = "Quelles compétences avez-vous acquises par les stages, emplois ou expériences pratiques ?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 11,
                            Number = 11,
                            Text = "Quelles compétences avez-vous acquises dans la famille, la communauté, les loisirs ou le bénévolat ?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 12,
                            Number = 12,
                            Text = "Quelles compétences souhaitez-vous encore développer ?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 13,
                            Number = 13,
                            Text = "Qu'est-ce qui est le plus important pour vous dans un travail ?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 14,
                            Number = 14,
                            Text = "Quelles causes, missions ou types de problèmes aimeriez-vous contribuer à résoudre ?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 15,
                            Number = 15,
                            Text = "Quel type de reconnaissance vous motive le plus ?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 16,
                            Number = 16,
                            Text = "Préférez-vous travailler seul, en équipe ou dans un mélange des deux ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 17,
                            Number = 17,
                            Text = "Préférez-vous un travail très structuré ou un travail qui laisse de la liberté d'organisation ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 18,
                            Number = 18,
                            Text = "Préférez-vous un environnement calme, dynamique, compétitif, créatif, social, technique ou administratif ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 19,
                            Number = 19,
                            Text = "Quel rythme de travail vous convient le mieux ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 20,
                            Number = 20,
                            Text = "Quels types de tâches évitez-vous ou vous épuisent rapidement ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 21,
                            Number = 21,
                            Text = "Quelles conditions de travail vous stressent fortement ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 22,
                            Number = 22,
                            Text = "Quels comportements ou styles de gestion vous démotivent ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 23,
                            Number = 23,
                            Text = "Quels domaines ou postes vous intéressent, mais pourraient ne pas correspondre à votre personnalité ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 24,
                            Number = 24,
                            Text = "Quelles activités ou situations vous placent dans un état d'esprit de réalisation, d'acceptation, d'accommodation, de collaboration, d'opposition, de contrainte ou de frustration ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 25,
                            Number = 25,
                            Text = "Quelles situations ou activités provoquent chez vous des émotions de joie, de colère ou de peine/tristesse ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 26,
                            Number = 26,
                            Text = "Quelles activités ou situations vous procurent des sentiments de satisfaction ou d'insatisfaction ?",
                            Theme = 5
                        });
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestionExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("CandidateQuestionExamples", "profil_candidat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            QuestionId = 1,
                            Text = "J'aime organiser des activités, même si cela demande beaucoup de préparation."
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            QuestionId = 1,
                            Text = "J'aime réparer des objets, chercher la panne et trouver une solution."
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            QuestionId = 1,
                            Text = "J'aime expliquer quelque chose à une autre personne jusqu'à ce qu'elle comprenne."
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 3,
                            QuestionId = 1,
                            Text = "J'aime écrire, lire, analyser ou résumer des informations."
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 4,
                            QuestionId = 1,
                            Text = "J'aime vendre, négocier ou convaincre une personne d'adhérer à une idée."
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 0,
                            QuestionId = 2,
                            Text = "Travailler avec des enfants, des jeunes ou des personnes en difficulté."
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            QuestionId = 2,
                            Text = "Résoudre des problèmes techniques ou pratiques."
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 2,
                            QuestionId = 2,
                            Text = "Créer des affiches, des contenus, des plans ou des présentations."
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 3,
                            QuestionId = 2,
                            Text = "Accueillir des clients et répondre à leurs besoins."
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 4,
                            QuestionId = 2,
                            Text = "Coordonner une équipe ou répartir les tâches."
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 0,
                            QuestionId = 3,
                            Text = "Lorsque je dessine, crée, bricole ou conçois quelque chose."
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 1,
                            QuestionId = 3,
                            Text = "Lorsque j'effectue des recherches sur Internet pour comprendre un sujet."
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 2,
                            QuestionId = 3,
                            Text = "Lorsque je cuisine, jardine ou réalise une activité manuelle."
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 3,
                            QuestionId = 3,
                            Text = "Lorsque je programme, calcule ou travaille sur un problème logique."
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 4,
                            QuestionId = 3,
                            Text = "Lorsque je discute avec quelqu'un pour l'écouter ou le conseiller."
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 0,
                            QuestionId = 4,
                            Text = "La santé, le bien-être et l'aide aux personnes."
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 1,
                            QuestionId = 4,
                            Text = "Les machines, l'électricité, l'informatique ou la technologie."
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 2,
                            QuestionId = 4,
                            Text = "L'éducation, la psychologie, la communication ou les relations humaines."
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 3,
                            QuestionId = 4,
                            Text = "Le commerce, l'entrepreneuriat, la gestion ou l'argent."
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 4,
                            QuestionId = 4,
                            Text = "L'environnement, l'agriculture, l'alimentation ou le développement durable."
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 0,
                            QuestionId = 5,
                            Text = "J'apprends facilement les langues."
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 1,
                            QuestionId = 5,
                            Text = "Je comprends vite les chiffres, les calculs ou les tableaux."
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 2,
                            QuestionId = 5,
                            Text = "Je retiens facilement les consignes pratiques."
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 3,
                            QuestionId = 5,
                            Text = "Je comprends rapidement le fonctionnement des appareils ou des outils."
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 4,
                            QuestionId = 5,
                            Text = "J'apprends facilement en observant les autres faire."
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 0,
                            QuestionId = 6,
                            Text = "Pour rédiger un texte, corriger un document ou préparer une présentation."
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 1,
                            QuestionId = 6,
                            Text = "Pour réparer un téléphone, un appareil ou résoudre un problème informatique."
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 2,
                            QuestionId = 6,
                            Text = "Pour organiser une fête, une réunion ou une activité."
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 3,
                            QuestionId = 6,
                            Text = "Pour expliquer une leçon, un devoir ou une procédure."
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 4,
                            QuestionId = 6,
                            Text = "Pour écouter un problème personnel et prodiguer un conseil."
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 0,
                            QuestionId = 7,
                            Text = "On me dit souvent que je suis patient."
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 1,
                            QuestionId = 7,
                            Text = "On me dit que je suis sérieux et fiable."
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 2,
                            QuestionId = 7,
                            Text = "On me reconnaît comme quelqu'un de créatif."
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 3,
                            QuestionId = 7,
                            Text = "On dit que je communique facilement avec les autres."
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 4,
                            QuestionId = 7,
                            Text = "On me dit que je suis courageux et persévérant."
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 0,
                            QuestionId = 8,
                            Text = "Je remarque rapidement lorsqu'une personne ne va pas bien."
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 1,
                            QuestionId = 8,
                            Text = "Je trouve facilement des solutions simples à des problèmes pratiques."
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 2,
                            QuestionId = 8,
                            Text = "Je mets de l'ordre dans les choses sans qu'on me le demande."
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 3,
                            QuestionId = 8,
                            Text = "Je motive les autres lorsqu'ils se découragent."
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 4,
                            QuestionId = 8,
                            Text = "Je mémorise facilement les détails importants."
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 0,
                            QuestionId = 9,
                            Text = "Lire, comprendre et résumer un texte."
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 1,
                            QuestionId = 9,
                            Text = "Utiliser un ordinateur, un logiciel de traitement de texte ou un tableur."
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 2,
                            QuestionId = 9,
                            Text = "Faire des calculs, gérer des données ou interpréter des résultats."
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 3,
                            QuestionId = 9,
                            Text = "Présenter un exposé devant un groupe."
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 4,
                            QuestionId = 9,
                            Text = "Comprendre les bases d'un domaine comme la comptabilité, l'électricité, la mécanique, la santé, l'enseignement."
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 0,
                            QuestionId = 10,
                            Text = "Accueillir des clients et répondre à leurs demandes."
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 1,
                            QuestionId = 10,
                            Text = "Respecter des horaires et des consignes de travail."
                        },
                        new
                        {
                            Id = 48,
                            DisplayOrder = 2,
                            QuestionId = 10,
                            Text = "Travailler en équipe avec des collègues."
                        },
                        new
                        {
                            Id = 49,
                            DisplayOrder = 3,
                            QuestionId = 10,
                            Text = "Utiliser des outils, machines, logiciels ou équipements professionnels."
                        },
                        new
                        {
                            Id = 50,
                            DisplayOrder = 4,
                            QuestionId = 10,
                            Text = "Gérer une petite caisse, un stock, une commande ou un planning."
                        },
                        new
                        {
                            Id = 51,
                            DisplayOrder = 0,
                            QuestionId = 11,
                            Text = "Encadrer des enfants ou des jeunes."
                        },
                        new
                        {
                            Id = 52,
                            DisplayOrder = 1,
                            QuestionId = 11,
                            Text = "Préparer des repas, organiser une activité ou gérer une petite équipe."
                        },
                        new
                        {
                            Id = 53,
                            DisplayOrder = 2,
                            QuestionId = 11,
                            Text = "Participer à des actions communautaires, religieuses, sportives ou sociales."
                        },
                        new
                        {
                            Id = 54,
                            DisplayOrder = 3,
                            QuestionId = 11,
                            Text = "Prendre soin d'une personne âgée, malade ou vulnérable."
                        },
                        new
                        {
                            Id = 55,
                            DisplayOrder = 4,
                            QuestionId = 11,
                            Text = "Gérer un petit commerce familial ou aider dans une activité agricole."
                        },
                        new
                        {
                            Id = 56,
                            DisplayOrder = 0,
                            QuestionId = 12,
                            Text = "Améliorer mon expression orale."
                        },
                        new
                        {
                            Id = 57,
                            DisplayOrder = 1,
                            QuestionId = 12,
                            Text = "Apprendre une langue étrangère."
                        },
                        new
                        {
                            Id = 58,
                            DisplayOrder = 2,
                            QuestionId = 12,
                            Text = "Maîtriser davantage l'informatique."
                        },
                        new
                        {
                            Id = 59,
                            DisplayOrder = 3,
                            QuestionId = 12,
                            Text = "Développer mes compétences en gestion ou en comptabilité."
                        },
                        new
                        {
                            Id = 60,
                            DisplayOrder = 4,
                            QuestionId = 12,
                            Text = "Apprendre à mieux gérer le stress et les priorités."
                        },
                        new
                        {
                            Id = 61,
                            DisplayOrder = 0,
                            QuestionId = 13,
                            Text = "Avoir un travail stable et sécurisant."
                        },
                        new
                        {
                            Id = 62,
                            DisplayOrder = 1,
                            QuestionId = 13,
                            Text = "Aider les autres et me sentir utile."
                        },
                        new
                        {
                            Id = 63,
                            DisplayOrder = 2,
                            QuestionId = 13,
                            Text = "Avoir un bon revenu pour soutenir ma famille."
                        },
                        new
                        {
                            Id = 64,
                            DisplayOrder = 3,
                            QuestionId = 13,
                            Text = "Apprendre constamment et progresser."
                        },
                        new
                        {
                            Id = 65,
                            DisplayOrder = 4,
                            QuestionId = 13,
                            Text = "Avoir de l'autonomie et pouvoir prendre des initiatives."
                        },
                        new
                        {
                            Id = 66,
                            DisplayOrder = 5,
                            QuestionId = 13,
                            Text = "Travailler dans un environnement respectueux."
                        },
                        new
                        {
                            Id = 67,
                            DisplayOrder = 0,
                            QuestionId = 14,
                            Text = "L'éducation des enfants et des jeunes."
                        },
                        new
                        {
                            Id = 68,
                            DisplayOrder = 1,
                            QuestionId = 14,
                            Text = "L'accès aux soins de santé."
                        },
                        new
                        {
                            Id = 69,
                            DisplayOrder = 2,
                            QuestionId = 14,
                            Text = "La pauvreté, le chômage ou l'exclusion sociale."
                        },
                        new
                        {
                            Id = 70,
                            DisplayOrder = 3,
                            QuestionId = 14,
                            Text = "La protection de l'environnement."
                        },
                        new
                        {
                            Id = 71,
                            DisplayOrder = 4,
                            QuestionId = 14,
                            Text = "L'amélioration du service aux clients."
                        },
                        new
                        {
                            Id = 72,
                            DisplayOrder = 5,
                            QuestionId = 14,
                            Text = "La sécurité, l'ordre ou la bonne organisation dans une entreprise."
                        },
                        new
                        {
                            Id = 73,
                            DisplayOrder = 0,
                            QuestionId = 15,
                            Text = "Être encouragé verbalement lorsque j'effectue bien mon travail."
                        },
                        new
                        {
                            Id = 74,
                            DisplayOrder = 1,
                            QuestionId = 15,
                            Text = "Recevoir plus de responsabilités."
                        },
                        new
                        {
                            Id = 75,
                            DisplayOrder = 2,
                            QuestionId = 15,
                            Text = "Voir concrètement les résultats de mes efforts."
                        },
                        new
                        {
                            Id = 76,
                            DisplayOrder = 3,
                            QuestionId = 15,
                            Text = "Progresser vers un meilleur poste."
                        },
                        new
                        {
                            Id = 77,
                            DisplayOrder = 4,
                            QuestionId = 15,
                            Text = "Sentir que je contribue à la réussite d'une équipe."
                        },
                        new
                        {
                            Id = 78,
                            DisplayOrder = 5,
                            QuestionId = 15,
                            Text = "Recevoir une rémunération juste pour le travail accompli."
                        },
                        new
                        {
                            Id = 79,
                            DisplayOrder = 0,
                            QuestionId = 16,
                            Text = "Je préfère travailler en équipe, car j'aime échanger avec les autres."
                        },
                        new
                        {
                            Id = 80,
                            DisplayOrder = 1,
                            QuestionId = 16,
                            Text = "Je préfère travailler seul lorsque je dois me concentrer."
                        },
                        new
                        {
                            Id = 81,
                            DisplayOrder = 2,
                            QuestionId = 16,
                            Text = "J'aime un mélange des deux : travailler seul pour avancer, puis échanger avec l'équipe."
                        },
                        new
                        {
                            Id = 82,
                            DisplayOrder = 3,
                            QuestionId = 16,
                            Text = "Je suis plus efficace lorsque les rôles de chacun sont bien définis."
                        },
                        new
                        {
                            Id = 83,
                            DisplayOrder = 4,
                            QuestionId = 16,
                            Text = "Je préfère un environnement où l'on s'entraide."
                        },
                        new
                        {
                            Id = 84,
                            DisplayOrder = 0,
                            QuestionId = 17,
                            Text = "Je préfère un travail structuré avec des consignes claires."
                        },
                        new
                        {
                            Id = 85,
                            DisplayOrder = 1,
                            QuestionId = 17,
                            Text = "J'aime avoir une certaine liberté pour organiser ma journée."
                        },
                        new
                        {
                            Id = 86,
                            DisplayOrder = 2,
                            QuestionId = 17,
                            Text = "Je suis à l'aise lorsque les objectifs sont clairs, même si la méthode reste flexible."
                        },
                        new
                        {
                            Id = 87,
                            DisplayOrder = 3,
                            QuestionId = 17,
                            Text = "J'ai besoin d'un cadre précis pour éviter la confusion."
                        },
                        new
                        {
                            Id = 88,
                            DisplayOrder = 4,
                            QuestionId = 17,
                            Text = "Je préfère les environnements où l'on peut proposer des idées nouvelles."
                        },
                        new
                        {
                            Id = 89,
                            DisplayOrder = 0,
                            QuestionId = 18,
                            Text = "Je préfère un environnement calme et organisé."
                        },
                        new
                        {
                            Id = 90,
                            DisplayOrder = 1,
                            QuestionId = 18,
                            Text = "Je suis motivé par un environnement dynamique avec beaucoup d'activités."
                        },
                        new
                        {
                            Id = 91,
                            DisplayOrder = 2,
                            QuestionId = 18,
                            Text = "J'aime les milieux sociaux où l'on rencontre beaucoup de personnes."
                        },
                        new
                        {
                            Id = 92,
                            DisplayOrder = 3,
                            QuestionId = 18,
                            Text = "Je préfère un environnement technique où l'on résout des problèmes concrets."
                        },
                        new
                        {
                            Id = 93,
                            DisplayOrder = 4,
                            QuestionId = 18,
                            Text = "Je suis à l'aise dans un cadre administratif avec des documents, des dossiers et des procédures."
                        },
                        new
                        {
                            Id = 94,
                            DisplayOrder = 5,
                            QuestionId = 18,
                            Text = "J'aime les environnements créatifs où l'on peut imaginer et construire quelque chose de nouveau."
                        },
                        new
                        {
                            Id = 95,
                            DisplayOrder = 0,
                            QuestionId = 19,
                            Text = "Un rythme régulier avec des horaires stables."
                        },
                        new
                        {
                            Id = 96,
                            DisplayOrder = 1,
                            QuestionId = 19,
                            Text = "Un rythme rapide avec des défis quotidiens."
                        },
                        new
                        {
                            Id = 97,
                            DisplayOrder = 2,
                            QuestionId = 19,
                            Text = "Un rythme flexible qui me permet de m'organiser."
                        },
                        new
                        {
                            Id = 98,
                            DisplayOrder = 3,
                            QuestionId = 19,
                            Text = "Un travail avec déplacements, car j'aime bouger."
                        },
                        new
                        {
                            Id = 99,
                            DisplayOrder = 4,
                            QuestionId = 19,
                            Text = "Un travail sans déplacements fréquents, car je préfère rester dans un même lieu."
                        },
                        new
                        {
                            Id = 100,
                            DisplayOrder = 5,
                            QuestionId = 19,
                            Text = "Un rythme saisonnier ou variable, si les périodes chargées sont bien organisées."
                        },
                        new
                        {
                            Id = 101,
                            DisplayOrder = 0,
                            QuestionId = 20,
                            Text = "Les tâches très répétitives sans variation."
                        },
                        new
                        {
                            Id = 102,
                            DisplayOrder = 1,
                            QuestionId = 20,
                            Text = "Les tâches qui demandent de parler constamment en public."
                        },
                        new
                        {
                            Id = 103,
                            DisplayOrder = 2,
                            QuestionId = 20,
                            Text = "Les travaux physiques très lourds."
                        },
                        new
                        {
                            Id = 104,
                            DisplayOrder = 3,
                            QuestionId = 20,
                            Text = "Les tâches administratives longues et sans contact humain."
                        },
                        new
                        {
                            Id = 105,
                            DisplayOrder = 4,
                            QuestionId = 20,
                            Text = "Les activités sans objectifs clairs."
                        },
                        new
                        {
                            Id = 106,
                            DisplayOrder = 5,
                            QuestionId = 20,
                            Text = "Les tâches où je dois agir trop vite sans comprendre ce qu'on attend de moi."
                        },
                        new
                        {
                            Id = 107,
                            DisplayOrder = 0,
                            QuestionId = 21,
                            Text = "Les changements de dernière minute sans explication."
                        },
                        new
                        {
                            Id = 108,
                            DisplayOrder = 1,
                            QuestionId = 21,
                            Text = "Le manque de respect ou les conflits fréquents."
                        },
                        new
                        {
                            Id = 109,
                            DisplayOrder = 2,
                            QuestionId = 21,
                            Text = "Les délais trop courts et mal organisés."
                        },
                        new
                        {
                            Id = 110,
                            DisplayOrder = 3,
                            QuestionId = 21,
                            Text = "Le bruit permanent ou l'agitation excessive."
                        },
                        new
                        {
                            Id = 111,
                            DisplayOrder = 4,
                            QuestionId = 21,
                            Text = "Le manque de matériel pour bien effectuer le travail."
                        },
                        new
                        {
                            Id = 112,
                            DisplayOrder = 5,
                            QuestionId = 21,
                            Text = "L'absence de soutien lorsqu'il y a des difficultés."
                        },
                        new
                        {
                            Id = 113,
                            DisplayOrder = 0,
                            QuestionId = 22,
                            Text = "Les critiques humiliantes ou publiques."
                        },
                        new
                        {
                            Id = 114,
                            DisplayOrder = 1,
                            QuestionId = 22,
                            Text = "Le favoritisme."
                        },
                        new
                        {
                            Id = 115,
                            DisplayOrder = 2,
                            QuestionId = 22,
                            Text = "Le manque de communication."
                        },
                        new
                        {
                            Id = 116,
                            DisplayOrder = 3,
                            QuestionId = 22,
                            Text = "Les ordres contradictoires."
                        },
                        new
                        {
                            Id = 117,
                            DisplayOrder = 4,
                            QuestionId = 22,
                            Text = "L'absence de reconnaissance."
                        },
                        new
                        {
                            Id = 118,
                            DisplayOrder = 5,
                            QuestionId = 22,
                            Text = "Le contrôle excessif sans confiance."
                        },
                        new
                        {
                            Id = 119,
                            DisplayOrder = 0,
                            QuestionId = 23,
                            Text = "La vente m'intéresse, mais je ne suis pas encore à l'aise avec la pression des objectifs."
                        },
                        new
                        {
                            Id = 120,
                            DisplayOrder = 1,
                            QuestionId = 23,
                            Text = "Le travail médical m'attire, mais je dois réfléchir à ma capacité à gérer la souffrance."
                        },
                        new
                        {
                            Id = 121,
                            DisplayOrder = 2,
                            QuestionId = 23,
                            Text = "La gestion d'équipe m'intéresse, mais je dois développer mon autorité et ma communication."
                        },
                        new
                        {
                            Id = 122,
                            DisplayOrder = 3,
                            QuestionId = 23,
                            Text = "L'entrepreneuriat m'attire, mais je dois mieux comprendre les risques financiers."
                        },
                        new
                        {
                            Id = 123,
                            DisplayOrder = 4,
                            QuestionId = 23,
                            Text = "L'informatique m'intéresse, mais je dois vérifier si j'aime vraiment travailler longtemps seul devant un écran."
                        },
                        new
                        {
                            Id = 124,
                            DisplayOrder = 0,
                            QuestionId = 24,
                            Text = "Je me sens en réalisation lorsque je termine une tâche utile ou visible."
                        },
                        new
                        {
                            Id = 125,
                            DisplayOrder = 1,
                            QuestionId = 24,
                            Text = "Je me sens en collaboration lorsque les rôles sont clairs et que chacun respecte l'autre."
                        },
                        new
                        {
                            Id = 126,
                            DisplayOrder = 2,
                            QuestionId = 24,
                            Text = "Je ressens de la frustration lorsque je dois travailler sans explication, sans moyens suffisants ou dans un climat de tension."
                        },
                        new
                        {
                            Id = 127,
                            DisplayOrder = 0,
                            QuestionId = 25,
                            Text = "Je ressens de la joie lorsque mon travail aide quelqu'un ou produit un résultat concret."
                        },
                        new
                        {
                            Id = 128,
                            DisplayOrder = 1,
                            QuestionId = 25,
                            Text = "Je ressens de la colère face à l'injustice ou au manque de respect."
                        },
                        new
                        {
                            Id = 129,
                            DisplayOrder = 2,
                            QuestionId = 25,
                            Text = "Je ressens de la tristesse lorsque mes efforts ne sont pas reconnus."
                        },
                        new
                        {
                            Id = 130,
                            DisplayOrder = 0,
                            QuestionId = 26,
                            Text = "Je ressens de la satisfaction quand mon travail a du sens et un résultat visible."
                        },
                        new
                        {
                            Id = 131,
                            DisplayOrder = 1,
                            QuestionId = 26,
                            Text = "Je ressens de l'insatisfaction lorsque mes efforts ne sont pas reconnus ou lorsque mes tâches n'ont pas de sens pour moi."
                        });
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateSynthesisTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CandidateSynthesisTags", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvCaracteristiquesPersonnelles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AptitudesProfessionnelles")
                        .HasColumnType("text");

                    b.Property<string>("AttitudesRelationnelles")
                        .HasColumnType("text");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("CapaciteSousPression")
                        .HasColumnType("text");

                    b.Property<string>("DisponibiliteMobilite")
                        .HasColumnType("text");

                    b.Property<string>("QualitesPersonnelles")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvCaracteristiquesPersonnelles", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvCompetencesEtudes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("CompetencesTechniques")
                        .HasColumnType("text");

                    b.Property<string>("ConnaissancesTheoriques")
                        .HasColumnType("text");

                    b.Property<string>("LanguesMaitrisees")
                        .HasColumnType("text");

                    b.Property<string>("OutilsLogicielsMethodes")
                        .HasColumnType("text");

                    b.Property<string>("SpecialitePrincipale")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvCompetencesEtudes", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvCoordonnees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseComplete")
                        .HasColumnType("text");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LieuNaissance")
                        .HasColumnType("text");

                    b.Property<string>("Nationalite")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Prenoms")
                        .HasColumnType("text");

                    b.Property<string>("ProfilOuPosteRecherche")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvCoordonnees", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<bool>("CertificationExactitude")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsentementConsultation")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("NomSignataire")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvDeclarations", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("CompetencesDeveloppees")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("EntrepriseOrganisationOuStage")
                        .HasColumnType("text");

                    b.Property<string>("FonctionOuActiviteExercee")
                        .HasColumnType("text");

                    b.Property<string>("Periode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CvExperiences", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvFormation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("DiplomeCertificatOuNiveau")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DomaineEtudes")
                        .HasColumnType("text");

                    b.Property<string>("Etablissement")
                        .HasColumnType("text");

                    b.Property<string>("Periode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CvFormations", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvLoisirs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivitesSportivesCulturelles")
                        .HasColumnType("text");

                    b.Property<string>("AutresCentresInteret")
                        .HasColumnType("text");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("EngagementsAssociatifs")
                        .HasColumnType("text");

                    b.Property<string>("LoisirsPreferes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("CvLoisirs", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CvReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("EntrepriseOrganisation")
                        .HasColumnType("text");

                    b.Property<string>("Fonction")
                        .HasColumnType("text");

                    b.Property<string>("LienAvecPostulant")
                        .HasColumnType("text");

                    b.Property<string>("NomPrenom")
                        .HasColumnType("text");

                    b.Property<string>("TelephoneOuEmail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CvReferences", "profil_candidat");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestionExample", b =>
                {
                    b.HasOne("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestion", null)
                        .WithMany("Examples")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilCandidat.Entities.CandidateQuestion", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
