// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.Entretien.Data;

#nullable disable

namespace Spectrometre.Modules.Entretien.Data.Migrations.Catalog
{
    [DbContext(typeof(EntretienCatalogDbContext))]
    [Migration("20260808195816_AddInterviewQuestionCatalog")]
    partial class AddInterviewQuestionCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.InterviewQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpectedElements")
                        .HasColumnType("text");

                    b.Property<int>("InterviewQuestionSubCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("SeedKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewQuestionSubCategoryId");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasFilter("\"SeedKey\" IS NOT NULL");

                    b.ToTable("InterviewQuestions", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.InterviewQuestionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SeedKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasFilter("\"SeedKey\" IS NOT NULL");

                    b.ToTable("InterviewQuestionCategories", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.InterviewQuestionSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InterviewQuestionCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SeedKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InterviewQuestionCategoryId");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasFilter("\"SeedKey\" IS NOT NULL");

                    b.ToTable("InterviewQuestionSubCategories", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.InterviewQuestion", b =>
                {
                    b.HasOne("Spectrometre.Modules.Entretien.Entities.InterviewQuestionSubCategory", "SubCategory")
                        .WithMany("Questions")
                        .HasForeignKey("InterviewQuestionSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.InterviewQuestionSubCategory", b =>
                {
                    b.HasOne("Spectrometre.Modules.Entretien.Entities.InterviewQuestionCategory", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("InterviewQuestionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.InterviewQuestionCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.InterviewQuestionSubCategory", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
