// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.ProfilEntreprise.Data;

#nullable disable

namespace Spectrometre.Modules.ProfilEntreprise.Data.Migrations
{
    [DbContext(typeof(ProfilEntrepriseDbContext))]
    [Migration("20260806205400_AddQuestionTextEn")]
    partial class AddQuestionTextEn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.ProfilEntreprise.Entities.CompanyAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId", "QuestionId")
                        .IsUnique();

                    b.ToTable("CompanyAnswers", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilEntreprise.Entities.CompanyCompatibilityCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("ComportementaleNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ComportementaleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CulturelleNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CulturelleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MotivationnelleNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("MotivationnelleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OrganisationnelleNotes")
                        .HasColumnType("text");

                    b.Property<string>("PointsVigilanceNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PointsVigilanceTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("RythmeTravail")
                        .HasColumnType("integer");

                    b.Property<string>("TechniqueNotes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("TechniqueTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId")
                        .IsUnique();

                    b.ToTable("CompanyCompatibilityCriteria", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilEntreprise.Entities.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CompanyProfiles", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilEntreprise.Entities.CompanyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextEn")
                        .HasColumnType("text");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("CompanyQuestions", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1,
                            Text = "Nom de l'entreprise ou de l'organisation",
                            TextEn = "Company or organization name",
                            Theme = 0
                        },
                        new
                        {
                            Id = 2,
                            Number = 2,
                            Text = "Secteur d'activité principal",
                            TextEn = "Main sector of activity",
                            Theme = 0
                        },
                        new
                        {
                            Id = 3,
                            Number = 3,
                            Text = "Localisation principale et zones d'intervention",
                            TextEn = "Main location and areas of operation",
                            Theme = 0
                        },
                        new
                        {
                            Id = 4,
                            Number = 4,
                            Text = "Taille de l'entreprise : petite, moyenne, grande, groupe, association, institution",
                            TextEn = "Company size: small, medium, large, group, association, institution",
                            Theme = 0
                        },
                        new
                        {
                            Id = 5,
                            Number = 5,
                            Text = "Ancienneté ou année de création",
                            TextEn = "Years in operation or founding year",
                            Theme = 0
                        },
                        new
                        {
                            Id = 6,
                            Number = 6,
                            Text = "Types de postes généralement proposés",
                            TextEn = "Types of positions generally offered",
                            Theme = 0
                        },
                        new
                        {
                            Id = 7,
                            Number = 7,
                            Text = "Quelle est la mission principale de l'entreprise ?",
                            TextEn = "What is the company's main mission?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 8,
                            Number = 8,
                            Text = "À quel besoin de la société, du marché ou de la communauté l'entreprise cherche-t-elle à répondre ?",
                            TextEn = "What need of society, the market or the community is the company trying to meet?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 9,
                            Number = 9,
                            Text = "Quelle vision l'entreprise poursuit-elle à moyen ou long terme ?",
                            TextEn = "What vision is the company pursuing in the medium or long term?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 10,
                            Number = 10,
                            Text = "Qu'est-ce qui rend l'entreprise utile, différente ou importante dans son secteur ?",
                            TextEn = "What makes the company useful, different or important in its sector?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 11,
                            Number = 11,
                            Text = "Quels problèmes l'entreprise souhaite-t-elle contribuer à résoudre ?",
                            TextEn = "What problems does the company want to help solve?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 12,
                            Number = 12,
                            Text = "Quelles sont les trois à cinq valeurs principales que l'entreprise souhaite incarner ?",
                            TextEn = "What are the three to five main values the company wants to embody?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 13,
                            Number = 13,
                            Text = "Comment ces valeurs se traduisent-elles dans les décisions quotidiennes ?",
                            TextEn = "How do these values translate into everyday decisions?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 14,
                            Number = 14,
                            Text = "Quelles valeurs sont attendues chez les collaborateurs ?",
                            TextEn = "What values are expected of employees?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 15,
                            Number = 15,
                            Text = "Quels comportements sont encouragés parce qu'ils correspondent à la culture de l'entreprise ?",
                            TextEn = "What behaviors are encouraged because they match the company's culture?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 16,
                            Number = 16,
                            Text = "Quels comportements sont incompatibles avec l'esprit de l'entreprise ?",
                            TextEn = "What behaviors are incompatible with the company's spirit?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 17,
                            Number = 17,
                            Text = "Comment décririez-vous le climat général de travail : calme, dynamique, exigeant, familial, compétitif, créatif, structuré, flexible ?",
                            TextEn = "How would you describe the overall work climate: calm, dynamic, demanding, family-like, competitive, creative, structured, flexible?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 18,
                            Number = 18,
                            Text = "Le travail est-il plutôt individuel, collectif ou mixte ?",
                            TextEn = "Is the work mostly individual, collective or a mix of both?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 19,
                            Number = 19,
                            Text = "Quelle place occupent les règles, procédures et consignes dans l'organisation du travail ?",
                            TextEn = "What role do rules, procedures and instructions play in how work is organized?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 20,
                            Number = 20,
                            Text = "Quelle place est laissée à l'initiative, à l'autonomie et à la créativité ?",
                            TextEn = "How much room is given to initiative, autonomy and creativity?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 21,
                            Number = 21,
                            Text = "Comment l'entreprise gère-t-elle les périodes de pression, d'urgence ou de forte activité ?",
                            TextEn = "How does the company handle periods of pressure, urgency or high activity?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 22,
                            Number = 22,
                            Text = "Quel style de leadership domine dans l'entreprise : directif, participatif, collaboratif, transformationnel, paternaliste, délégatif, orienté résultats ?",
                            TextEn = "What leadership style dominates in the company: directive, participative, collaborative, transformational, paternalistic, delegative, results-oriented?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 23,
                            Number = 23,
                            Text = "Comment les responsables donnent-ils les consignes et suivent-ils le travail ?",
                            TextEn = "How do managers give instructions and follow up on work?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 24,
                            Number = 24,
                            Text = "Quelle place les employés ont-ils dans la prise de décision ?",
                            TextEn = "What role do employees have in decision-making?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 25,
                            Number = 25,
                            Text = "Comment les responsables accompagnent-ils les nouveaux collaborateurs ?",
                            TextEn = "How do managers support new employees?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 26,
                            Number = 26,
                            Text = "Comment les erreurs sont-elles traitées : sanction, apprentissage, correction, accompagnement, discussion ?",
                            TextEn = "How are mistakes handled: sanction, learning, correction, support, discussion?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 27,
                            Number = 27,
                            Text = "Quel type de collaborateur réussit le mieux sous ce mode de leadership ?",
                            TextEn = "What type of employee thrives best under this leadership style?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 28,
                            Number = 28,
                            Text = "Comment les collaborateurs communiquent-ils entre eux : oralement, par écrit, en réunions, par messagerie, par rapports ?",
                            TextEn = "How do employees communicate with each other: verbally, in writing, in meetings, by messaging, through reports?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 29,
                            Number = 29,
                            Text = "Le climat relationnel est-il plutôt formel, informel, hiérarchique, familial, direct, diplomatique ou réservé ?",
                            TextEn = "Is the relational climate mostly formal, informal, hierarchical, family-like, direct, diplomatic or reserved?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 30,
                            Number = 30,
                            Text = "Comment les désaccords ou conflits sont-ils généralement gérés ?",
                            TextEn = "How are disagreements or conflicts usually handled?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 31,
                            Number = 31,
                            Text = "Quelle importance l'entreprise accorde-t-elle à l'écoute, au respect, à la politesse et à la coopération ?",
                            TextEn = "How much importance does the company place on listening, respect, politeness and cooperation?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 32,
                            Number = 32,
                            Text = "Quels comportements relationnels sont particulièrement appréciés dans l'entreprise ?",
                            TextEn = "What relational behaviors are particularly valued in the company?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 33,
                            Number = 33,
                            Text = "Quels comportements relationnels créent des difficultés dans l'entreprise ?",
                            TextEn = "What relational behaviors create difficulties in the company?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 34,
                            Number = 34,
                            Text = "Comment l'entreprise reconnaît-elle les efforts et les bons résultats ?",
                            TextEn = "How does the company recognize effort and good results?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 35,
                            Number = 35,
                            Text = "Quels types de motivation sont les plus présents : salaire, responsabilité, reconnaissance, progression, stabilité, autonomie, esprit d'équipe ?",
                            TextEn = "What types of motivation are most present: salary, responsibility, recognition, progression, stability, autonomy, team spirit?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 36,
                            Number = 36,
                            Text = "Quelles possibilités d'apprentissage, de formation ou d'évolution sont proposées ?",
                            TextEn = "What learning, training or advancement opportunities are offered?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 37,
                            Number = 37,
                            Text = "Comment l'entreprise accompagne-t-elle les personnes qui veulent progresser ?",
                            TextEn = "How does the company support people who want to advance?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 38,
                            Number = 38,
                            Text = "Quels signes montrent qu'un collaborateur est bien intégré et apprécié dans l'entreprise ?",
                            TextEn = "What signs show that an employee is well integrated and valued in the company?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 39,
                            Number = 39,
                            Text = "Quels sont les horaires habituels et le rythme de travail ?",
                            TextEn = "What are the usual hours and work pace?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 40,
                            Number = 40,
                            Text = "Le travail exige-t-il des déplacements, de la mobilité, une disponibilité particulière ou des horaires variables ?",
                            TextEn = "Does the job require travel, mobility, special availability or variable hours?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 41,
                            Number = 41,
                            Text = "Quelles sont les principales contraintes physiques, psychologiques, relationnelles ou organisationnelles ?",
                            TextEn = "What are the main physical, psychological, relational or organizational constraints?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 42,
                            Number = 42,
                            Text = "Quel niveau d'autonomie est attendu du collaborateur ?",
                            TextEn = "What level of autonomy is expected of the employee?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 43,
                            Number = 43,
                            Text = "Quel niveau de pression, de rapidité ou de précision le travail demande-t-il ?",
                            TextEn = "What level of pressure, speed or precision does the job require?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 44,
                            Number = 44,
                            Text = "Quels moyens l'entreprise met-elle à disposition pour permettre de bien travailler ?",
                            TextEn = "What resources does the company provide to enable good work?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 45,
                            Number = 45,
                            Text = "Quelles qualités personnelles permettent de bien réussir dans l'entreprise ?",
                            TextEn = "What personal qualities help someone succeed in the company?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 46,
                            Number = 46,
                            Text = "Quelles compétences techniques ou professionnelles sont les plus recherchées ?",
                            TextEn = "What technical or professional skills are most sought after?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 47,
                            Number = 47,
                            Text = "Quel type de personnalité s'intègre facilement dans l'équipe ?",
                            TextEn = "What type of personality fits easily into the team?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 48,
                            Number = 48,
                            Text = "Quel type de candidat pourrait rencontrer des difficultés dans cet environnement ?",
                            TextEn = "What type of candidate might struggle in this environment?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 49,
                            Number = 49,
                            Text = "Quelles valeurs personnelles du candidat doivent être compatibles avec celles de l'entreprise ?",
                            TextEn = "What personal values of the candidate must be compatible with the company's?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 50,
                            Number = 50,
                            Text = "Notre entreprise est principalement caractérisée par...",
                            TextEn = "Our company is mainly characterized by...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 51,
                            Number = 51,
                            Text = "Nos trois valeurs les plus importantes sont...",
                            TextEn = "Our three most important values are...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 52,
                            Number = 52,
                            Text = "Notre style de leadership est plutôt...",
                            TextEn = "Our leadership style is more...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 53,
                            Number = 53,
                            Text = "Notre mode relationnel est plutôt...",
                            TextEn = "Our relational style is more...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 54,
                            Number = 54,
                            Text = "Les collaborateurs qui réussissent le mieux chez nous sont ceux qui...",
                            TextEn = "The employees who succeed best here are those who...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 55,
                            Number = 55,
                            Text = "Les candidats doivent être particulièrement attentifs à...",
                            TextEn = "Candidates should pay particular attention to...",
                            Theme = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
