// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.ProfilEntreprise.Data;

#nullable disable

namespace Spectrometre.Modules.ProfilEntreprise.Data.Migrations
{
    [DbContext(typeof(ProfilEntrepriseDbContext))]
    [Migration("20260805135044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.ProfilEntreprise.Entities.CompanyAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId", "QuestionId")
                        .IsUnique();

                    b.ToTable("CompanyAnswers", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilEntreprise.Entities.CompanyCompatibilityCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("ComportementaleText")
                        .HasColumnType("text");

                    b.Property<string>("CulturelleText")
                        .HasColumnType("text");

                    b.Property<string>("MotivationnelleText")
                        .HasColumnType("text");

                    b.Property<string>("OrganisationnelleText")
                        .HasColumnType("text");

                    b.Property<string>("PointsVigilanceText")
                        .HasColumnType("text");

                    b.Property<string>("TechniqueText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId")
                        .IsUnique();

                    b.ToTable("CompanyCompatibilityCriteria", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilEntreprise.Entities.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CompanyProfiles", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.ProfilEntreprise.Entities.CompanyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("CompanyQuestions", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1,
                            Text = "Nom de l'entreprise ou de l'organisation",
                            Theme = 0
                        },
                        new
                        {
                            Id = 2,
                            Number = 2,
                            Text = "Secteur d'activité principal",
                            Theme = 0
                        },
                        new
                        {
                            Id = 3,
                            Number = 3,
                            Text = "Localisation principale et zones d'intervention",
                            Theme = 0
                        },
                        new
                        {
                            Id = 4,
                            Number = 4,
                            Text = "Taille de l'entreprise : petite, moyenne, grande, groupe, association, institution",
                            Theme = 0
                        },
                        new
                        {
                            Id = 5,
                            Number = 5,
                            Text = "Ancienneté ou année de création",
                            Theme = 0
                        },
                        new
                        {
                            Id = 6,
                            Number = 6,
                            Text = "Types de postes généralement proposés",
                            Theme = 0
                        },
                        new
                        {
                            Id = 7,
                            Number = 7,
                            Text = "Quelle est la mission principale de l'entreprise ?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 8,
                            Number = 8,
                            Text = "À quel besoin de la société, du marché ou de la communauté l'entreprise cherche-t-elle à répondre ?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 9,
                            Number = 9,
                            Text = "Quelle vision l'entreprise poursuit-elle à moyen ou long terme ?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 10,
                            Number = 10,
                            Text = "Qu'est-ce qui rend l'entreprise utile, différente ou importante dans son secteur ?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 11,
                            Number = 11,
                            Text = "Quels problèmes l'entreprise souhaite-t-elle contribuer à résoudre ?",
                            Theme = 1
                        },
                        new
                        {
                            Id = 12,
                            Number = 12,
                            Text = "Quelles sont les trois à cinq valeurs principales que l'entreprise souhaite incarner ?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 13,
                            Number = 13,
                            Text = "Comment ces valeurs se traduisent-elles dans les décisions quotidiennes ?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 14,
                            Number = 14,
                            Text = "Quelles valeurs sont attendues chez les collaborateurs ?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 15,
                            Number = 15,
                            Text = "Quels comportements sont encouragés parce qu'ils correspondent à la culture de l'entreprise ?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 16,
                            Number = 16,
                            Text = "Quels comportements sont incompatibles avec l'esprit de l'entreprise ?",
                            Theme = 2
                        },
                        new
                        {
                            Id = 17,
                            Number = 17,
                            Text = "Comment décririez-vous le climat général de travail : calme, dynamique, exigeant, familial, compétitif, créatif, structuré, flexible ?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 18,
                            Number = 18,
                            Text = "Le travail est-il plutôt individuel, collectif ou mixte ?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 19,
                            Number = 19,
                            Text = "Quelle place occupent les règles, procédures et consignes dans l'organisation du travail ?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 20,
                            Number = 20,
                            Text = "Quelle place est laissée à l'initiative, à l'autonomie et à la créativité ?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 21,
                            Number = 21,
                            Text = "Comment l'entreprise gère-t-elle les périodes de pression, d'urgence ou de forte activité ?",
                            Theme = 3
                        },
                        new
                        {
                            Id = 22,
                            Number = 22,
                            Text = "Quel style de leadership domine dans l'entreprise : directif, participatif, collaboratif, transformationnel, paternaliste, délégatif, orienté résultats ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 23,
                            Number = 23,
                            Text = "Comment les responsables donnent-ils les consignes et suivent-ils le travail ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 24,
                            Number = 24,
                            Text = "Quelle place les employés ont-ils dans la prise de décision ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 25,
                            Number = 25,
                            Text = "Comment les responsables accompagnent-ils les nouveaux collaborateurs ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 26,
                            Number = 26,
                            Text = "Comment les erreurs sont-elles traitées : sanction, apprentissage, correction, accompagnement, discussion ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 27,
                            Number = 27,
                            Text = "Quel type de collaborateur réussit le mieux sous ce mode de leadership ?",
                            Theme = 4
                        },
                        new
                        {
                            Id = 28,
                            Number = 28,
                            Text = "Comment les collaborateurs communiquent-ils entre eux : oralement, par écrit, en réunions, par messagerie, par rapports ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 29,
                            Number = 29,
                            Text = "Le climat relationnel est-il plutôt formel, informel, hiérarchique, familial, direct, diplomatique ou réservé ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 30,
                            Number = 30,
                            Text = "Comment les désaccords ou conflits sont-ils généralement gérés ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 31,
                            Number = 31,
                            Text = "Quelle importance l'entreprise accorde-t-elle à l'écoute, au respect, à la politesse et à la coopération ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 32,
                            Number = 32,
                            Text = "Quels comportements relationnels sont particulièrement appréciés dans l'entreprise ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 33,
                            Number = 33,
                            Text = "Quels comportements relationnels créent des difficultés dans l'entreprise ?",
                            Theme = 5
                        },
                        new
                        {
                            Id = 34,
                            Number = 34,
                            Text = "Comment l'entreprise reconnaît-elle les efforts et les bons résultats ?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 35,
                            Number = 35,
                            Text = "Quels types de motivation sont les plus présents : salaire, responsabilité, reconnaissance, progression, stabilité, autonomie, esprit d'équipe ?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 36,
                            Number = 36,
                            Text = "Quelles possibilités d'apprentissage, de formation ou d'évolution sont proposées ?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 37,
                            Number = 37,
                            Text = "Comment l'entreprise accompagne-t-elle les personnes qui veulent progresser ?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 38,
                            Number = 38,
                            Text = "Quels signes montrent qu'un collaborateur est bien intégré et apprécié dans l'entreprise ?",
                            Theme = 6
                        },
                        new
                        {
                            Id = 39,
                            Number = 39,
                            Text = "Quels sont les horaires habituels et le rythme de travail ?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 40,
                            Number = 40,
                            Text = "Le travail exige-t-il des déplacements, de la mobilité, une disponibilité particulière ou des horaires variables ?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 41,
                            Number = 41,
                            Text = "Quelles sont les principales contraintes physiques, psychologiques, relationnelles ou organisationnelles ?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 42,
                            Number = 42,
                            Text = "Quel niveau d'autonomie est attendu du collaborateur ?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 43,
                            Number = 43,
                            Text = "Quel niveau de pression, de rapidité ou de précision le travail demande-t-il ?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 44,
                            Number = 44,
                            Text = "Quels moyens l'entreprise met-elle à disposition pour permettre de bien travailler ?",
                            Theme = 7
                        },
                        new
                        {
                            Id = 45,
                            Number = 45,
                            Text = "Quelles qualités personnelles permettent de bien réussir dans l'entreprise ?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 46,
                            Number = 46,
                            Text = "Quelles compétences techniques ou professionnelles sont les plus recherchées ?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 47,
                            Number = 47,
                            Text = "Quel type de personnalité s'intègre facilement dans l'équipe ?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 48,
                            Number = 48,
                            Text = "Quel type de candidat pourrait rencontrer des difficultés dans cet environnement ?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 49,
                            Number = 49,
                            Text = "Quelles valeurs personnelles du candidat doivent être compatibles avec celles de l'entreprise ?",
                            Theme = 8
                        },
                        new
                        {
                            Id = 50,
                            Number = 50,
                            Text = "Notre entreprise est principalement caractérisée par...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 51,
                            Number = 51,
                            Text = "Nos trois valeurs les plus importantes sont...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 52,
                            Number = 52,
                            Text = "Notre style de leadership est plutôt...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 53,
                            Number = 53,
                            Text = "Notre mode relationnel est plutôt...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 54,
                            Number = 54,
                            Text = "Les collaborateurs qui réussissent le mieux chez nous sont ceux qui...",
                            Theme = 9
                        },
                        new
                        {
                            Id = 55,
                            Number = 55,
                            Text = "Les candidats doivent être particulièrement attentifs à...",
                            Theme = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
