// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.SuiviEvolutif.Data;

#nullable disable

namespace Spectrometre.Modules.SuiviEvolutif.Data.Migrations.Entreprise
{
    [DbContext(typeof(SuiviEvolutifEntrepriseDbContext))]
    partial class SuiviEvolutifEntrepriseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.SuiviEvolutif.Entities.CompanyProfileChangeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AncienneValeur")
                        .HasColumnType("text");

                    b.Property<string>("Champ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Horodatage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NouvelleValeur")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId", "Horodatage");

                    b.ToTable("Entries", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
