// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.SuiviEmployes.Data;

#nullable disable

namespace Spectrometre.Modules.SuiviEmployes.Data.Migrations
{
    [DbContext(typeof(SuiviEmployesDbContext))]
    [Migration("20260808233423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.SuiviEmployes.Entities.AnalyseIaEmploye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalyseMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EnCours")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("GenereeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCompanyLinkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserCompanyLinkId", "DataHash")
                        .IsUnique();

                    b.ToTable("AnalysesIaEmploye", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.SuiviEmployes.Entities.EvaluationEmploye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CritereId")
                        .HasColumnType("integer");

                    b.Property<int>("DaySequence")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EvaluationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("PosteId")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreActuel")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreSouhaite")
                        .HasColumnType("integer");

                    b.Property<int>("UserCompanyLinkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserCompanyLinkId", "PosteId", "EvaluationDate");

                    b.HasIndex("UserCompanyLinkId", "CritereId", "EvaluationDate", "DaySequence")
                        .IsUnique();

                    b.ToTable("EvaluationsEmploye", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.SuiviEmployes.Entities.EvaluationEmployeCloturee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EvaluationDate")
                        .HasColumnType("date");

                    b.Property<int>("PosteId")
                        .HasColumnType("integer");

                    b.Property<int>("UserCompanyLinkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserCompanyLinkId", "PosteId", "EvaluationDate")
                        .IsUnique();

                    b.ToTable("EvaluationsEmployeCloturees", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.SuiviEmployes.Entities.EvaluationObjectifs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archivee")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<string>("EvaluateurUserId")
                        .HasColumnType("text");

                    b.Property<int>("UserCompanyLinkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserCompanyLinkId", "DateDebut", "DateFin");

                    b.ToTable("EvaluationsObjectifs", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.SuiviEmployes.Entities.Objectif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Atteinte")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EvaluationObjectifsId")
                        .HasColumnType("integer");

                    b.Property<string>("Moyens")
                        .HasColumnType("text");

                    b.Property<int?>("Note")
                        .HasColumnType("integer");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationObjectifsId");

                    b.ToTable("Objectifs", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.SuiviEmployes.Entities.ValidationSocioProEmploye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PosteId")
                        .HasColumnType("integer");

                    b.Property<int>("UserCompanyLinkId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserCompanyLinkId", "PosteId")
                        .IsUnique();

                    b.ToTable("ValidationsSocioProEmploye", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.SuiviEmployes.Entities.Objectif", b =>
                {
                    b.HasOne("Spectrometre.Modules.SuiviEmployes.Entities.EvaluationObjectifs", "EvaluationObjectifs")
                        .WithMany("Objectifs")
                        .HasForeignKey("EvaluationObjectifsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationObjectifs");
                });

            modelBuilder.Entity("Spectrometre.Modules.SuiviEmployes.Entities.EvaluationObjectifs", b =>
                {
                    b.Navigation("Objectifs");
                });
#pragma warning restore 612, 618
        }
    }
}
