// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.Compatibilite.Data;

#nullable disable

namespace Spectrometre.Modules.Compatibilite.Data.Migrations
{
    [DbContext(typeof(CompatibiliteDbContext))]
    partial class CompatibiliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.Compatibilite.Entities.CompatibilityResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreComportementale")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreCulturelle")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreGlobal")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreMotivationnelle")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreOrganisationnelle")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreTechnique")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CompatibilityResults", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Compatibilite.Entities.CompatibilityVigilancePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompatibilityResultId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompatibilityResultId");

                    b.ToTable("CompatibilityVigilancePoint", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Compatibilite.Entities.CompatibilityWeightSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Axis")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightPercent")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Axis")
                        .IsUnique();

                    b.ToTable("CompatibilityWeightSettings", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Axis = 0,
                            WeightPercent = 20m
                        },
                        new
                        {
                            Id = 2,
                            Axis = 1,
                            WeightPercent = 20m
                        },
                        new
                        {
                            Id = 3,
                            Axis = 2,
                            WeightPercent = 20m
                        },
                        new
                        {
                            Id = 4,
                            Axis = 3,
                            WeightPercent = 20m
                        },
                        new
                        {
                            Id = 5,
                            Axis = 4,
                            WeightPercent = 20m
                        });
                });

            modelBuilder.Entity("Spectrometre.Modules.Compatibilite.Entities.CompatibilityVigilancePoint", b =>
                {
                    b.HasOne("Spectrometre.Modules.Compatibilite.Entities.CompatibilityResult", null)
                        .WithMany("VigilancePoints")
                        .HasForeignKey("CompatibilityResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.Compatibilite.Entities.CompatibilityResult", b =>
                {
                    b.Navigation("VigilancePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
