// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.GestionDuTemps.Data;

#nullable disable

namespace Spectrometre.Modules.GestionDuTemps.Data.Migrations
{
    [DbContext(typeof(GestionDuTempsDbContext))]
    [Migration("20260806124017_AddProfilPsychosocialReflexionSynthese")]
    partial class AddProfilPsychosocialReflexionSynthese
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gestion_du_temps")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.Activite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateActivite")
                        .HasColumnType("date");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeDeTempsId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("TypeDeTempsId");

                    b.HasIndex("UserId", "DateActivite", "HeureDebut");

                    b.ToTable("Activites", "gestion_du_temps");
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClotureLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DemarreLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroCycle")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"Statut\" = 'EnCours'");

                    b.HasIndex("UserId", "NumeroCycle")
                        .IsUnique();

                    b.ToTable("Cycles", "gestion_du_temps");
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.KanbanStatut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiviteId")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TimerDebutUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TimerDureeReelleMs")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId")
                        .IsUnique();

                    b.ToTable("KanbanStatuts", "gestion_du_temps");
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.ProfilPsychosocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivitesRessourcantes")
                        .HasColumnType("text");

                    b.Property<int?>("AutonomieGestion")
                        .HasColumnType("integer");

                    b.Property<string>("CapaciteNon")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Culpabilite")
                        .HasColumnType("text");

                    b.Property<int>("CycleId")
                        .HasColumnType("integer");

                    b.Property<string>("DecisionsPrecipitees")
                        .HasColumnType("text");

                    b.Property<bool?>("DeplacementsImprevus")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Desequilibres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("DifficultesConcentration")
                        .HasColumnType("text");

                    b.Property<string>("DirectionAdmin")
                        .HasColumnType("text");

                    b.Property<string>("DirectionFamille")
                        .HasColumnType("text");

                    b.Property<string>("DirectionPerso")
                        .HasColumnType("text");

                    b.Property<string>("DirectionPro")
                        .HasColumnType("text");

                    b.Property<string>("DirectionSocial")
                        .HasColumnType("text");

                    b.Property<string>("DirectionSommeil")
                        .HasColumnType("text");

                    b.Property<string>("DureeTrajets")
                        .HasColumnType("text");

                    b.Property<bool?>("EcransAvantSommeil")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("EmotionsNegatives")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("EmotionsPositives")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool?>("EngagementCommunautaire")
                        .HasColumnType("boolean");

                    b.Property<string>("EngagementNature")
                        .HasColumnType("text");

                    b.Property<string>("GestionAdmin")
                        .HasColumnType("text");

                    b.Property<string>("HoraireTravail")
                        .HasColumnType("text");

                    b.Property<string>("InterruptionsTravail")
                        .HasColumnType("text");

                    b.Property<string>("ManqueTempsPerso")
                        .HasColumnType("text");

                    b.Property<string>("ModeTravail")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ObjectifsProfessionnels")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Obstacles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OuiTropFacile")
                        .HasColumnType("text");

                    b.Property<string>("PlanificationAvance")
                        .HasColumnType("text");

                    b.Property<bool?>("ProcheMalade")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ReveilsNocturnes")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RituelsQuotidiens")
                        .HasColumnType("boolean");

                    b.Property<int?>("SatisfactionAdmin")
                        .HasColumnType("integer");

                    b.Property<int?>("SatisfactionFamille")
                        .HasColumnType("integer");

                    b.Property<int?>("SatisfactionPerso")
                        .HasColumnType("integer");

                    b.Property<int?>("SatisfactionPro")
                        .HasColumnType("integer");

                    b.Property<int?>("SatisfactionSocial")
                        .HasColumnType("integer");

                    b.Property<int?>("SatisfactionSommeil")
                        .HasColumnType("integer");

                    b.Property<string>("SentimentPression")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("SommeilCoucher")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("SommeilLever")
                        .HasColumnType("time without time zone");

                    b.Property<string>("SommeilReparateur")
                        .HasColumnType("text");

                    b.Property<string>("StressAdmin")
                        .HasColumnType("text");

                    b.Property<bool?>("SurchargePrevisible")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TempsPersoQuotidien")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Tendances")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ToleranceImprevu")
                        .HasColumnType("text");

                    b.Property<string>("TravailHorsHeures")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("UtiliseAgenda")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CycleId")
                        .IsUnique();

                    b.ToTable("ProfilsPsychosociaux", "gestion_du_temps");
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.ReflexionConsciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DateEcheance")
                        .HasColumnType("date");

                    b.PrimitiveCollection<List<string>>("Ressentis")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SituationActuelle")
                        .HasColumnType("text");

                    b.Property<bool?>("SourceIdentifiee")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Sources")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CycleId")
                        .IsUnique();

                    b.ToTable("ReflexionsConscientes", "gestion_du_temps");
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.Synthese", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertesJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleId")
                        .HasColumnType("integer");

                    b.Property<bool>("GenereeParIa")
                        .HasColumnType("boolean");

                    b.Property<string>("IndiceCommentaire")
                        .HasColumnType("text");

                    b.Property<int>("IndiceEquilibre")
                        .HasColumnType("integer");

                    b.Property<string>("MaturiteCommentaire")
                        .HasColumnType("text");

                    b.Property<int>("NiveauMaturite")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilSnapshotHash")
                        .HasColumnType("text");

                    b.Property<string>("ProfilTexte")
                        .HasColumnType("text");

                    b.Property<string>("ProfilType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommandationsJson")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CycleId")
                        .IsUnique();

                    b.ToTable("Syntheses", "gestion_du_temps");
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.TypeDeTemps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HeureFin")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdreAffichage")
                        .HasColumnType("integer");

                    b.Property<string>("RecurrenceJours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "Cle")
                        .IsUnique();

                    b.ToTable("TypesDeTemps", "gestion_du_temps");
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.Activite", b =>
                {
                    b.HasOne("Spectrometre.Modules.GestionDuTemps.Entities.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spectrometre.Modules.GestionDuTemps.Entities.TypeDeTemps", null)
                        .WithMany()
                        .HasForeignKey("TypeDeTempsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.KanbanStatut", b =>
                {
                    b.HasOne("Spectrometre.Modules.GestionDuTemps.Entities.Activite", null)
                        .WithMany()
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.ProfilPsychosocial", b =>
                {
                    b.HasOne("Spectrometre.Modules.GestionDuTemps.Entities.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.ReflexionConsciente", b =>
                {
                    b.HasOne("Spectrometre.Modules.GestionDuTemps.Entities.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.Synthese", b =>
                {
                    b.HasOne("Spectrometre.Modules.GestionDuTemps.Entities.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.GestionDuTemps.Entities.TypeDeTemps", b =>
                {
                    b.HasOne("Spectrometre.Modules.GestionDuTemps.Entities.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
