// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.Recrutement.Data;

#nullable disable

namespace Spectrometre.Modules.Recrutement.Data.Migrations
{
    [DbContext(typeof(RecrutementDbContext))]
    [Migration("20260808102649_AddAnalyseIaPoste")]
    partial class AddAnalyseIaPoste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.AnalyseIaPoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalyseTexte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidatureId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("GenereeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GenereeParIa")
                        .HasColumnType("boolean");

                    b.Property<string>("HashSnapshot")
                        .HasColumnType("text");

                    b.Property<int>("PosteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.HasIndex("PosteId", "CandidatureId")
                        .IsUnique();

                    b.ToTable("AnalysesIaPoste", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.Candidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstPreselectionne")
                        .HasColumnType("boolean");

                    b.Property<int>("PosteId")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PosteId", "CandidateProfileId")
                        .IsUnique();

                    b.ToTable("Candidatures", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.CritereEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NiveauRequis")
                        .HasColumnType("integer");

                    b.Property<int>("OrdreAffichage")
                        .HasColumnType("integer");

                    b.Property<int>("PosteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PosteId", "OrdreAffichage");

                    b.ToTable("CriteresEvaluation", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.EvaluationCritereCandidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatureId")
                        .HasColumnType("integer");

                    b.Property<int>("CritereId")
                        .HasColumnType("integer");

                    b.Property<int>("NiveauFinal")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CritereId");

                    b.HasIndex("CandidatureId", "CritereId")
                        .IsUnique();

                    b.ToTable("EvaluationsCriteresCandidature", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.GuideDeuxiemeEntrevue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoriteResponsabilite")
                        .HasColumnType("text");

                    b.Property<string>("Echeances")
                        .HasColumnType("text");

                    b.Property<string>("MissionLivrables")
                        .HasColumnType("text");

                    b.Property<string>("Objectifs")
                        .HasColumnType("text");

                    b.Property<int>("PosteId")
                        .HasColumnType("integer");

                    b.Property<string>("SituationQualitative")
                        .HasColumnType("text");

                    b.Property<string>("SituationQuantitative")
                        .HasColumnType("text");

                    b.Property<string>("Suivi")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PosteId")
                        .IsUnique();

                    b.ToTable("GuidesDeuxiemeEntrevue", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.Poste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departement")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Postes", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.AnalyseIaPoste", b =>
                {
                    b.HasOne("Spectrometre.Modules.Recrutement.Entities.Candidature", null)
                        .WithMany()
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.EvaluationCritereCandidature", b =>
                {
                    b.HasOne("Spectrometre.Modules.Recrutement.Entities.Candidature", null)
                        .WithMany("EvaluationsFinales")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spectrometre.Modules.Recrutement.Entities.CritereEvaluation", null)
                        .WithMany()
                        .HasForeignKey("CritereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.GuideDeuxiemeEntrevue", b =>
                {
                    b.HasOne("Spectrometre.Modules.Recrutement.Entities.Poste", null)
                        .WithMany()
                        .HasForeignKey("PosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.Candidature", b =>
                {
                    b.Navigation("EvaluationsFinales");
                });
#pragma warning restore 612, 618
        }
    }
}
