// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.Recrutement.Data;

#nullable disable

namespace Spectrometre.Modules.Recrutement.Data.Migrations
{
    [DbContext(typeof(RecrutementDbContext))]
    partial class RecrutementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.AnalyseIaPoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalyseTexte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidatureId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("GenereeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GenereeParIa")
                        .HasColumnType("boolean");

                    b.Property<string>("HashSnapshot")
                        .HasColumnType("text");

                    b.Property<int>("PosteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PosteId", "CandidatureId")
                        .IsUnique();

                    b.ToTable("AnalysesIaPoste", "public");
                });

            modelBuilder.Entity("Spectrometre.Modules.Recrutement.Entities.GuideDeuxiemeEntrevue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoriteResponsabilite")
                        .HasColumnType("text");

                    b.Property<string>("Echeances")
                        .HasColumnType("text");

                    b.Property<string>("MissionLivrables")
                        .HasColumnType("text");

                    b.Property<string>("Objectifs")
                        .HasColumnType("text");

                    b.Property<int>("PosteId")
                        .HasColumnType("integer");

                    b.Property<string>("SituationQualitative")
                        .HasColumnType("text");

                    b.Property<string>("SituationQuantitative")
                        .HasColumnType("text");

                    b.Property<string>("Suivi")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PosteId")
                        .IsUnique();

                    b.ToTable("GuidesDeuxiemeEntrevue", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
