// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.JeunesPrestataires.Data;

#nullable disable

namespace Spectrometre.Modules.JeunesPrestataires.Data.Migrations
{
    [DbContext(typeof(JeunesPrestatairesDbContext))]
    [Migration("20260819224919_AddAutoObservationQuestionnaire")]
    partial class AddAutoObservationQuestionnaire
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jeunes_prestataires")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.JeunesPrestataires.Entities.AutoObservationReponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JeuneProfileId")
                        .HasColumnType("integer");

                    b.Property<int?>("NumericValue")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JeuneProfileId", "QuestionKey")
                        .IsUnique();

                    b.ToTable("AutoObservationReponses", "jeunes_prestataires");
                });

            modelBuilder.Entity("Spectrometre.Modules.JeunesPrestataires.Entities.AutoObservationSectionProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JeuneProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JeuneProfileId", "SectionKey")
                        .IsUnique();

                    b.ToTable("AutoObservationSectionProgress", "jeunes_prestataires");
                });

            modelBuilder.Entity("Spectrometre.Modules.JeunesPrestataires.Entities.AutoObservationSyntheseGeneree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GenereeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JeuneProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JeuneProfileId")
                        .IsUnique();

                    b.ToTable("AutoObservationSynthesesGenerees", "jeunes_prestataires");
                });

            modelBuilder.Entity("Spectrometre.Modules.JeunesPrestataires.Entities.ConsentementParental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutorisationDonneesEtImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutorisationMissions")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutorisationRevenus")
                        .HasColumnType("boolean");

                    b.Property<string>("AutreAffectation")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EngagementCollaborerCoach")
                        .HasColumnType("boolean");

                    b.Property<bool>("EngagementEncouragerCharte")
                        .HasColumnType("boolean");

                    b.Property<bool>("EngagementInformerContraintes")
                        .HasColumnType("boolean");

                    b.Property<bool>("EngagementScolariteSanteEquilibre")
                        .HasColumnType("boolean");

                    b.Property<bool>("EngagementSignalerMissionInadaptee")
                        .HasColumnType("boolean");

                    b.Property<int>("JeuneProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("ModalitesVersement")
                        .HasColumnType("text");

                    b.Property<string>("NomJeuneConfirmation")
                        .HasColumnType("text");

                    b.Property<string>("NomParent1Confirmation")
                        .HasColumnType("text");

                    b.Property<string>("NomParent2Confirmation")
                        .HasColumnType("text");

                    b.Property<string>("Parent1Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Parent1Email")
                        .HasColumnType("text");

                    b.Property<string>("Parent1Lien")
                        .HasColumnType("text");

                    b.Property<string>("Parent1Nom")
                        .HasColumnType("text");

                    b.Property<string>("Parent1Telephone")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Email")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Lien")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Nom")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Telephone")
                        .HasColumnType("text");

                    b.Property<decimal?>("PartArgentDePochePourcent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PartParascolairePourcent")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValideLe")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JeuneProfileId")
                        .IsUnique();

                    b.ToTable("ConsentementsParentaux", "jeunes_prestataires");
                });

            modelBuilder.Entity("Spectrometre.Modules.JeunesPrestataires.Entities.InvitationJeunePrestataire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<int>("InvitationId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId")
                        .IsUnique();

                    b.ToTable("InvitationsJeunesPrestataires", "jeunes_prestataires");
                });

            modelBuilder.Entity("Spectrometre.Modules.JeunesPrestataires.Entities.JeuneProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<int>("InvitationId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JeuneProfiles", "jeunes_prestataires");
                });
#pragma warning restore 612, 618
        }
    }
}
