// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.Entretien.Data;

#nullable disable

namespace Spectrometre.Modules.Entretien.Data.Migrations
{
    [DbContext(typeof(EntretienDbContext))]
    [Migration("20260805212744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.InterviewGenerationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SeuilAxeFaiblePercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InterviewGenerationSettings", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SeuilAxeFaiblePercent = 60
                        });
                });

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.QuestionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Axis")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Gabarit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sens")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Axis", "Sens", "DisplayOrder");

                    b.ToTable("QuestionTemplates", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Axis = 0,
                            DisplayOrder = 0,
                            Gabarit = "Quelles sont, selon vous, les compétences techniques qui vous manquent encore pour être pleinement opérationnel sur ce poste ?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Axis = 0,
                            DisplayOrder = 0,
                            Gabarit = "Quel accompagnement ou quelle formation l'entreprise prévoit-elle pour combler un éventuel écart de compétences techniques ?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Axis = 1,
                            DisplayOrder = 0,
                            Gabarit = "Pouvez-vous décrire une situation récente où votre façon de travailler au quotidien a été mise à l'épreuve ?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Axis = 1,
                            DisplayOrder = 0,
                            Gabarit = "Quels comportements professionnels l'entreprise valorise-t-elle le plus au quotidien, au-delà de ce qui est affiché ?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Axis = 2,
                            DisplayOrder = 0,
                            Gabarit = "Qu'est-ce qui, dans la culture d'une entreprise, vous a déjà mis mal à l'aise par le passé ?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Axis = 2,
                            DisplayOrder = 0,
                            Gabarit = "Comment la culture d'entreprise affichée se traduit-elle concrètement dans les décisions du quotidien ?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Axis = 3,
                            DisplayOrder = 0,
                            Gabarit = "Vous avez indiqué tolérer un rythme « {rythmeCandidat} », alors que ce poste est annoncé avec un rythme « {rythmeEntreprise} » — comment envisagez-vous cet écart au quotidien ?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Axis = 3,
                            DisplayOrder = 0,
                            Gabarit = "Le poste est annoncé avec un rythme « {rythmeEntreprise} » — à quoi ressemble concrètement une semaine type pour quelqu'un qui tolère plutôt un rythme « {rythmeCandidat} » ?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Axis = 4,
                            DisplayOrder = 0,
                            Gabarit = "Qu'est-ce qui vous ferait perdre votre motivation le plus rapidement dans ce poste ?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Axis = 4,
                            DisplayOrder = 0,
                            Gabarit = "Qu'est-ce que l'entreprise met concrètement en place pour nourrir la motivation de ses équipes ?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 0,
                            Gabarit = "Vous avez signalé « {tag} » comme un point de vigilance potentiel — pouvez-vous préciser ce que cela représente concrètement pour vous, et comment vous l'avez géré par le passé ?",
                            Sens = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 0,
                            Gabarit = "L'entreprise a également identifié « {tag} » comme un point de vigilance — comment cela se manifeste-t-il concrètement au quotidien dans l'équipe ?",
                            Sens = 1,
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
