// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spectrometre.Modules.Entretien.Data;

#nullable disable

namespace Spectrometre.Modules.Entretien.Data.Migrations
{
    [DbContext(typeof(EntretienDbContext))]
    [Migration("20260806203434_AddGabaritEnToQuestionTemplate")]
    partial class AddGabaritEnToQuestionTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.InterviewGenerationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SeuilAxeFaiblePercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InterviewGenerationSettings", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SeuilAxeFaiblePercent = 60
                        });
                });

            modelBuilder.Entity("Spectrometre.Modules.Entretien.Entities.QuestionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Axis")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Gabarit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GabaritEn")
                        .HasColumnType("text");

                    b.Property<int>("Sens")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Axis", "Sens", "DisplayOrder");

                    b.ToTable("QuestionTemplates", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Axis = 0,
                            DisplayOrder = 0,
                            Gabarit = "Quelles sont, selon vous, les compétences techniques qui vous manquent encore pour être pleinement opérationnel sur ce poste ?",
                            GabaritEn = "In your view, which technical skills are you still missing to be fully operational in this role?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Axis = 0,
                            DisplayOrder = 0,
                            Gabarit = "Quel accompagnement ou quelle formation l'entreprise prévoit-elle pour combler un éventuel écart de compétences techniques ?",
                            GabaritEn = "What support or training does the company plan to offer to close any technical skills gap?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Axis = 1,
                            DisplayOrder = 0,
                            Gabarit = "Pouvez-vous décrire une situation récente où votre façon de travailler au quotidien a été mise à l'épreuve ?",
                            GabaritEn = "Can you describe a recent situation where your day-to-day way of working was put to the test?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Axis = 1,
                            DisplayOrder = 0,
                            Gabarit = "Quels comportements professionnels l'entreprise valorise-t-elle le plus au quotidien, au-delà de ce qui est affiché ?",
                            GabaritEn = "Which professional behaviors does the company value most day-to-day, beyond what's officially stated?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Axis = 2,
                            DisplayOrder = 0,
                            Gabarit = "Qu'est-ce qui, dans la culture d'une entreprise, vous a déjà mis mal à l'aise par le passé ?",
                            GabaritEn = "What, in a company's culture, has made you uncomfortable in the past?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Axis = 2,
                            DisplayOrder = 0,
                            Gabarit = "Comment la culture d'entreprise affichée se traduit-elle concrètement dans les décisions du quotidien ?",
                            GabaritEn = "How does the company's stated culture concretely translate into day-to-day decisions?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Axis = 3,
                            DisplayOrder = 0,
                            Gabarit = "Vous avez indiqué tolérer un rythme « {rythmeCandidat} », alors que ce poste est annoncé avec un rythme « {rythmeEntreprise} » — comment envisagez-vous cet écart au quotidien ?",
                            GabaritEn = "You indicated you can tolerate a \"{rythmeCandidat}\" pace, while this role is advertised with a \"{rythmeEntreprise}\" pace — how do you see yourself handling this gap day-to-day?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Axis = 3,
                            DisplayOrder = 0,
                            Gabarit = "Le poste est annoncé avec un rythme « {rythmeEntreprise} » — à quoi ressemble concrètement une semaine type pour quelqu'un qui tolère plutôt un rythme « {rythmeCandidat} » ?",
                            GabaritEn = "This role is advertised with a \"{rythmeEntreprise}\" pace — what does a typical week concretely look like for someone who instead tolerates a \"{rythmeCandidat}\" pace?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Axis = 4,
                            DisplayOrder = 0,
                            Gabarit = "Qu'est-ce qui vous ferait perdre votre motivation le plus rapidement dans ce poste ?",
                            GabaritEn = "What would make you lose motivation fastest in this role?",
                            Sens = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Axis = 4,
                            DisplayOrder = 0,
                            Gabarit = "Qu'est-ce que l'entreprise met concrètement en place pour nourrir la motivation de ses équipes ?",
                            GabaritEn = "What does the company concretely put in place to nurture its teams' motivation?",
                            Sens = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 0,
                            Gabarit = "Vous avez signalé « {tag} » comme un point de vigilance potentiel — pouvez-vous préciser ce que cela représente concrètement pour vous, et comment vous l'avez géré par le passé ?",
                            GabaritEn = "You flagged \"{tag}\" as a potential point of caution — can you clarify what this concretely means to you, and how you've handled it in the past?",
                            Sens = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 0,
                            Gabarit = "L'entreprise a également identifié « {tag} » comme un point de vigilance — comment cela se manifeste-t-il concrètement au quotidien dans l'équipe ?",
                            GabaritEn = "The company also identified \"{tag}\" as a point of caution — how does this concretely show up day-to-day within the team?",
                            Sens = 1,
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
